/**
 *
 */
package fr.android.earthdawn.character.enums;

import java.util.Arrays;
import java.util.List;

import fr.android.earthdawn.character.actions.impl.EndurancePostAction;
import fr.android.earthdawn.character.actions.impl.InitPostAction;
import fr.android.earthdawn.character.actions.impl.InitPreAction;
import fr.android.earthdawn.character.actions.impl.RemoveTmpModAction;
import fr.android.earthdawn.character.actions.impl.TempModAction;

/**
 * @author DrMabulle
 *
 */
public enum Disciplines
{
    Archer("Archer",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.ArmesTir, 1, true, null, null), /* "armes de trait" dans la liste de disciplines */
            new Talent(Talents.Esquive, 1, false, null, null),
            new Talent(Talents.FlecheDirection, 1, true, null, null),
            new Talent(Talents.MarqueMystique, 1, true, null, null),
            new Talent(Talents.TirInfaillible, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 6, 5),
            new Talent(Talents.ArmesJet, 2, true, null, null),
            new Talent(Talents.Sprint, 2, false, null, null),
            new Talent(Talents.FlecheEnflammee, 3, true, null, null),
            new Talent(Talents.Stabilite, 3, false, null, null),
            new Talent(Talents.ArmesMelee, 4, false, null, null),
            new Talent(Talents.TissageArcher, 4, true, null, null),
            new Talent(Talents.MarqueParalysante, 5, true, null, null), /* "immobilisation de la cible" dans la liste des disciplines */
            new Talent(Talents.PremiereImpression, 5, false, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.DonLangues, 6, false, null, null),
            new Talent(Talents.Ricochet, 6, true, null, null),
            new Talent(Talents.Anticipation, 7, false, null, null),
            new Talent(Talents.RappelFleches, 7, true, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.OeilAigle, 8, true, null, null),
            new Talent(Talents.DeuxiemeAttaque, 8, true, null, null),
            new Talent(Talents.DeplacementSilencieux, 9, false, null, null),
            new Talent(Talents.LocalisationTireur, 9, true, null, null),
            new Talent(Talents.TirImpressionnant, 9, true, null, null),
            new Talent(Talents.AttaqueCourse, 10, true, null, null),
            new Talent(Talents.TirAvertissement, 10, true, null, null),
            new Talent(Talents.TirAveugle, 11, true, null, null),
            new Talent(Talents.DominationFleches, 11, true, null, null), /* "tir rapide" dans le bouquin, corrigé en "domination des flèches" en erratum */
            new Talent(Talents.CreationFleches, 12, true, null, null),
            new Talent(Talents.DetectionDefautsArmure, 12, false, null, null),
            new Talent(Talents.DefenseAmelioree, 13, false, null, null), /*simplement "défense" dans le bouquin */
            new Talent(Talents.FlecheHurlante, 13, true, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.DeuxiemeChance, 14, false, null, null),
            new Talent(Talents.TirMultiple, 14, true, null, null),
            new Talent(Talents.ArcVent, 15, false, null, null),
            new Talent(Talents.ArmeEtheree, 15, true, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 4),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 5),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 6),
            // XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.ArmesTir), 7),
            Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 8),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 9),
            Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
            Perks.get(Mod.get(Pointcuts.INIT, 1), 10),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
            Perks.get(Mod.get(Pointcuts.INIT, 1), 11),
            Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
            Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 12),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 13),
            Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
            Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 14),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 15),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 15))),


    Cavalier("Cavalier",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.AcrobatiesEnSelle, 1, true, null, null),
            new Talent(Talents.Apprivoisement, 1, false, null, null),
            new Talent(Talents.Esquive, 1, false, null, null),
            new Talent(Talents.ChargeDevastatrice, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 7, 6),
            new Talent(Talents.OrdreEmpathique, 2, true, null, null),
            new Talent(Talents.PartageSang, 2, true, null, null),
            new Talent(Talents.AttaqueTournoyante, 3, false, null, null),
            new Talent(Talents.MontureSpectrale, 3, true, null, null),
            new Talent(Talents.SangFroid, 4, true, null, null),
            new Talent(Talents.TissageCavalier, 4, true, null, null),
            new Talent(Talents.DefenseTournoyante, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.TenueSelle, 5, true, null, null),
            new Talent(Talents.DominationAnimaux, 6, false, null, null),
            new Talent(Talents.EnduranceMonture, 6, false, null, null),
            new Talent(Talents.ArmesTir, 7, false, null, null), /* "armes de trait" dans la liste de disciplines */
            new Talent(Talents.ImpressionDurable, 7, false, null, null),
            new Talent(Talents.ChargeTerrifiante, 8, true, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.Pietinement, 8, true, null, null),
            new Talent(Talents.AppelMonture, 9, true, null, null),
            new Talent(Talents.AttaquePlongeante, 9, false, null, null),
            new Talent(Talents.Ralliement, 9, true, null, null),
            new Talent(Talents.DefiChampion, 10, false, null, null),
            new Talent(Talents.ProtectionMonture, 10, false, null, null),
            new Talent(Talents.DressageMonture, 11, false, null, null), /* "domptage de monture" dans la liste de discipline */
            new Talent(Talents.SoinCompagnonAnimal, 11, true, null, null),
            new Talent(Talents.AttaqueEnchainee, 12, false, null, null),
            new Talent(Talents.RegardTerrifiantMaitre, 12, true, null, null),
            new Talent(Talents.PerceArmure, 13, true, null, null), /* "passe-bouclier" dans la liste des disciplines */
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.UltimeSursaut, 13, false, null, null),
            new Talent(Talents.DetectionDefautsArmure, 14, false, null, null),
            new Talent(Talents.MontureAgressive, 14, true, null, null),
            new Talent(Talents.ArmeEtheree, 15, false, null, null),
            new Talent(Talents.ChargeMultiple, 15, true, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.STR), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.END), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.CHA), 6),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.Monture), 7),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 8),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
 			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 15),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 15),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 15))),


    Eclaireur("Eclaireur",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.DeplacementSilencieux, 1, true, null, null),
            new Talent(Talents.Escalade, 1, true, null, null),
            new Talent(Talents.Esquive, 1, true, null, null),
            new Talent(Talents.Pistage, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 6, 5),
            new Talent(Talents.LectureEcriture, 2, false, null, null),
            new Talent(Talents.Manoeuvre, 2, false, null, null),
            new Talent(Talents.Sprint, 3, false, null, null),
            new Talent(Talents.VisionAstrale, 3, true, null, null),
            new Talent(Talents.Riposte, 4, false, null, null),
            new Talent(Talents.TissageEclaireur, 4, true, null, null),
            new Talent(Talents.EsquivePieges, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.SensSerrures, 5, false, null, null),
            new Talent(Talents.DonLangues, 6, false, null, null),
            new Talent(Talents.SautGeant, 6, false, null, null),
            new Talent(Talents.DetectionPieges, 7, true, null, null),
            new Talent(Talents.EnduranceFroid, 7, true, null, null),
            new Talent(Talents.ArmesTir, 8, false, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.MarcheVents, 8, true, null, null),
            new Talent(Talents.AnalyseCreature, 9, true, null, null),
            new Talent(Talents.Anticipation, 9, false, null, null),
            new Talent(Talents.DetectionArmes, 9, true, null, null),
            new Talent(Talents.DeviationProjectiles, 10, false, null, null),
            new Talent(Talents.LocalisationTireur, 10, true, null, null),
            new Talent(Talents.DeguisementMagique, 11, false, null, null),
            new Talent(Talents.Stabilite, 11, false, null, null),
            new Talent(Talents.DefenseAmelioree, 12, true, null, null),
            new Talent(Talents.ViveLame, 12, false, null, null),
            new Talent(Talents.DetectionPoison, 13, true, null, null),
            new Talent(Talents.GuideElementaire, 13, true, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.DeuxiemeChance, 14, false, null, null),
            new Talent(Talents.ResistancePoison, 14, true, null, null),
            new Talent(Talents.ArmeEtheree, 15, false, null, null),
            new Talent(Talents.LocalisationEcho, 15, true, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 6),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 7),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 8),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 14),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 15),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 15),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 15))),

    EcumeurCiel("Ecumeur du Ciel",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.CriGuerre, 1, true, null, null),
            new Talent(Talents.Esquive, 1, false, null, null),
            new Talent(Talents.NavigationAerienne, 1, true, null, null),
            new Talent(Talents.SangFeu, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 8, 6),
            new Talent(Talents.CoupBouclier, 2, true, null, null),
            new Talent(Talents.SautGeant, 2, true, null, null),
            new Talent(Talents.ChutePlume, 3, true, null, null),
            new Talent(Talents.CombatMainsNues, 3, false, null, null),
            new Talent(Talents.CoupPiedRapide, 4, false, null, null),
            new Talent(Talents.TissageEcumeurCiel, 4, true, null, null),
            new Talent(Talents.Recel, 5, false, null, null),
            new Talent(Talents.RugissementGuerre, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.AttaqueEnchainee, 6, true, null, null),
            new Talent(Talents.RegardFroid, 6, true, null, null),
            new Talent(Talents.ArmesJet, 7, false, null, null),
            new Talent(Talents.DonLangues, 7, false, null, null),
            new Talent(Talents.ArmesTir, 8, false, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.CoupDevastateur, 8, true, null, null),
            new Talent(Talents.CoeurLion, 9, true, null, null),
            new Talent(Talents.DeuxiemeAttaque, 9, true, null, null),
            new Talent(Talents.EnduranceFroid, 9, true, null, null),
            new Talent(Talents.HacheTonnerre, 10, true, null, null),
            new Talent(Talents.PerceArmure, 10, false, null, null),
            new Talent(Talents.DefenseAmelioree, 11, false, null, null),
            new Talent(Talents.DestructionArme, 11, true, null, null),
            new Talent(Talents.AttaqueCritique, 12, false, null, null),
            new Talent(Talents.Vitalite, 12, false, null, null),
            new Talent(Talents.AttaqueMatrices, 13, false, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.ViveLame, 13, false, null, null),
            new Talent(Talents.Hurlement, 14, false, null, null),
            new Talent(Talents.TirRapide, 14, false, null, null),
            new Talent(Talents.FlecheHurlante, 15, false, null, null),
            new Talent(Talents.PeauPierre, 15, true, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.STR), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.END), 6),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.ArmesMelee), 7),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 8),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 9),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 13),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 15))),

    Elementaliste("Elémentaliste",
        Arrays.asList(new Talent(Talents.Incantation, 1, true, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.LectureEcriture, 1, false, null, null),
            new Talent(Talents.LectureEcritureMagie, 1, false, null, null),
            new Talent(Talents.MatriceSort, 1, false, null, null),
            new Talent(Talents.MatriceSort, 1, false, null, null),
            new Talent(Talents.TissageElementaliste, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 4, 3),
            new Talent(Talents.GuerisonFeu, 2, true, null, null),
            new Talent(Talents.MatriceSort, 2, false, null, null),
            new Talent(Talents.LangageVent, 3, true, null, null),
            new Talent(Talents.LanguesElementaires, 3, true, null, null),
            new Talent(Talents.MatriceSort, 4, false, null, null),
            new Talent(Talents.VisionAstrale, 4, false, null, null),
            new Talent(Talents.ImmobilisationElementaire, 5, true, null, null),
            new Talent(Talents.Invocation, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.Determination, 6, false, null, null),
            new Talent(Talents.PurificationFroid, 6, true, null, null),
            new Talent(Talents.Enracinement, 7, false, null, null),
            new Talent(Talents.MatriceAmelioree, 7, false, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.ControleTemperature, 8, true, null, null),
            new Talent(Talents.MatriceAmelioree, 8, false, null, null),
            new Talent(Talents.GuideElementaire, 9, true, null, null),
            new Talent(Talents.MatriceRenforcee, 9, false, null, null),
            new Talent(Talents.ProtectionContreMetal, 9, true, null, null),
            new Talent(Talents.AbriVegetal, 10, true, null, null),
            new Talent(Talents.RemodelageObjet, 10, true, null, null),
            new Talent(Talents.AnimationObjet, 11, false, null, null),
            new Talent(Talents.CercleInvocation, 11, true, null, null),
            new Talent(Talents.MatriceRenforcee, 12, false, null, null),
            new Talent(Talents.NegociationCreatureInvoquee, 12, true, null, null),
            new Talent(Talents.DanseEaux, 13, true, null, null),
            new Talent(Talents.TerreFlottante, 13, true, null, null), /* "terre mouvante" dans la liste des disciplines */
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.ArmureTellurique, 14, true, null, null),
            new Talent(Talents.MatricePartagee, 14, false, null, null),
            new Talent(Talents.MaintienFilament, 15, false, null, null),
            new Talent(Talents.MatricePartagee, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.VOL), 5),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 7),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.Incantation), 8),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 13),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 2), 14),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 15))),

    Forgeron("Forgeron",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false, null, null),
            new Talent(Talents.Esquive, 1, false, null, null),
            new Talent(Talents.HistoireArmes, 1, true, null, null),
            new Talent(Talents.PerfectionnementLame, 1, true, null, null),
            new Talent(Talents.VolonteFer, 1, true, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 6, 5),
            new Talent(Talents.LectureEcriture, 2, false, null, null),
            new Talent(Talents.Marchandage, 2, true, null, null),
            new Talent(Talents.ContreMalediction, 3, true, null, null),
            new Talent(Talents.DetectionArmes, 3, true, null, null),
            new Talent(Talents.DonLangues, 4, false, null, null),
            new Talent(Talents.TissageForgeron, 4, true, null, null),
            new Talent(Talents.AlterationArmeTir, 5, true, null, null),
            new Talent(Talents.Endurcissement, 5, true, new RemoveTmpModAction(Pointcuts.UNCOUNSCIOUSNESS_THRESHOLD, Pointcuts.HEALTH_POINTS, Pointcuts.WOUND_THRESHOLD), new EndurancePostAction(Pointcuts.UNCOUNSCIOUSNESS_THRESHOLD, Pointcuts.HEALTH_POINTS, Pointcuts.WOUND_THRESHOLD)),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.DetectionDefautsArmure, 6, true, null, null),
            new Talent(Talents.DissimulationArme, 6, false, null, null),
            new Talent(Talents.Desarmement, 7, false, null, null),
            new Talent(Talents.EndurcissementAutrui, 7, true, null, null),
            new Talent(Talents.AmeliorationLame, 8, true, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.LectureEcritureMagie, 8, false, null, null),
            new Talent(Talents.Incantation, 9, false, null, null),
            new Talent(Talents.MatriceAmelioree, 9, false, null, null),
            new Talent(Talents.TissageElementaliste, 9, false, null, null),
            new Talent(Talents.DetectionArmesMagiques, 10, true, null, null),
            new Talent(Talents.ProtectionContreMetal, 10, false, null, null),
            new Talent(Talents.PerfectionnementArmure, 11, true, null, null),
            new Talent(Talents.SangFeu, 11, false, null, null),
            new Talent(Talents.DeteriorationArme, 12, true, null, null),
            new Talent(Talents.RevelationDefautsArmure, 12, true, null, null),
            new Talent(Talents.AmeliorationArmure, 13, true, null, null),
            new Talent(Talents.AttaqueCritique, 13, false, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.MatriceRenforcee, 14, false, null, null),
            new Talent(Talents.PremierCerclePerfection, 14, true, null, null),
            new Talent(Talents.DeuxiemeChance, 15, false, null, null),
            new Talent(Talents.MatricePartagee, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 6),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.VOL), 7),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 8),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 9),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 12),
 			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 13),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 2), 15),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 15))),

    Guerrier("Guerrier",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
            new Talent(Talents.AttaqueAcrobatique, 1, false, null, null),
            new Talent(Talents.CombatMainsNues, 1, true, null, null),
            new Talent(Talents.DanseAirs, 1, false, new InitPreAction(Pointcuts.INIT), new InitPostAction(Pointcuts.INIT)),
            new Talent(Talents.PeauBois, 1, true, null, new TempModAction(Pointcuts.HEALTH_POINTS, Pointcuts.UNCOUNSCIOUSNESS_THRESHOLD)),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 9, 7),
            new Talent(Talents.Anticipation, 2, true, null, null),
            new Talent(Talents.ArmesJet, 2, false, null, null),
            new Talent(Talents.Esquive, 3, true, null, null),
            new Talent(Talents.VivaciteTigre, 3, false, new InitPreAction(Pointcuts.INIT_MOD), new InitPostAction(Pointcuts.INIT_MOD)),
            new Talent(Talents.AttaquePlongeante, 4, true, null, null),
            new Talent(Talents.TissageGuerrier, 4, true, null, null),
            new Talent(Talents.CoupPiedRapide, 5, true, null, null),
            new Talent(Talents.MarcheVents, 5, false, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.ArmesTir, 6, false, null, null),
            new Talent(Talents.UltimeSursaut, 6, true, null, null),
            new Talent(Talents.DeuxiemeAttaque, 7, false, null, null),
            new Talent(Talents.PeauTellurique, 7, false, null, null),
            new Talent(Talents.AttaqueAstrale, 8, true, null, null),
            new Talent(Talents.AttaqueCobra, 8, true, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.DeuxiemeArme, 9, true, null, null),
            new Talent(Talents.DeviationProjectiles, 9, false, null, null),
            new Talent(Talents.PatteVelours, 9, false, null, null),
            new Talent(Talents.ArmeCorporelle, 10, true, null, null),
            new Talent(Talents.AttaqueMatrices, 10, false, null, null),
            new Talent(Talents.DetectionDefautsArmure, 11, false, null, null),
            new Talent(Talents.Vitalite, 11, false, null, null),
            new Talent(Talents.Cameleon, 12, false, null, null),
            new Talent(Talents.Desarconnement, 12, true, null, null),
            new Talent(Talents.PeauPierre, 13, true, null, null),
            new Talent(Talents.GuideElementaire, 13, false, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.AttaqueDecisive, 14, false, null, null),
            new Talent(Talents.DeuxiemeChance, 14, false, null, null),
            new Talent(Talents.AttaqueMultiple, 15, true, null, null),
            new Talent(Talents.AuraProtectrice, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.VOL), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.STR), 6),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.ArmesMelee), 7),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.CombatMainsNues), 8),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 9),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 10),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
 			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
 			Perks.get(Mod.get(Pointcuts.INIT, 1), 12),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 14),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 15),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 2), 15))),

    Illusionniste("Illusionniste",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.Incantation, 1, true, null, null),
            new Talent(Talents.LectureEcriture, 1, false, null, null),
            new Talent(Talents.LectureEcritureMagie, 1, true, null, null),
            new Talent(Talents.MatriceSort, 1, false, null, null),
            new Talent(Talents.MatriceSort, 1, false, null, null),
            new Talent(Talents.TissageIllusionniste, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 4, 3),
            new Talent(Talents.DeguisementMagique, 2, true, null, null),
            new Talent(Talents.MatriceSort, 2, false, null, null),
            new Talent(Talents.DonLangues, 3, false, null, null),
            new Talent(Talents.MortFeinte, 3, true, null, null),
            new Talent(Talents.FauxSemblants, 4, true, null, null),
            new Talent(Talents.MatriceSort, 4, false, null, null),
            new Talent(Talents.Determination, 5, false, null, null),
            new Talent(Talents.RejetResponsabilite, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.Escamotage, 6, true, null, null),
            new Talent(Talents.VisionAstrale, 6, true, null, null),
            new Talent(Talents.Distraction, 7, true, null, null),
            new Talent(Talents.MatriceAmelioree, 7, false, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.MatriceAmelioree, 8, false, null, null),
            new Talent(Talents.VisionVeritable, 8, true, null, null),
            new Talent(Talents.DetectionMensonges, 9, true, null, null),
            new Talent(Talents.MatriceRenforcee, 9, false, null, null),
            new Talent(Talents.SangFroid, 9, true, null, null),
            new Talent(Talents.MemoireImages, 10, false, null, null),
            new Talent(Talents.OndeMentale, 10, true, null, null),
            new Talent(Talents.MatriceRenforcee, 11, false, null, null),
            new Talent(Talents.Hypnose, 11, true, null, null),
            new Talent(Talents.PenseeSecrete, 12, true, null, null),
            new Talent(Talents.VisageMiroir, 12, true, null, null),
            new Talent(Talents.AttaqueMatrices, 13, false, null, null),
            new Talent(Talents.MatricePartagee, 13, false, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.MatricePartagee, 14, false, null, null),
            new Talent(Talents.TissageMultiple, 14, true, null, null),
            new Talent(Talents.DeuxiemeChance, 15, true, null, null),
            new Talent(Talents.MatricePartagee, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.VOL), 6),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.Incantation), 7),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 8),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 11),
 			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 2), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 15),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 15),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 15))),

    MaitreArmes("Maitre d'Armes",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.Esquive, 1, true, null, null),
            new Talent(Talents.Manoeuvre, 1, true, null, null),
            new Talent(Talents.Sarcasmes, 1, false, null, null),
            new Talent(Talents.Stabilite, 1, false, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 7, 6),
            new Talent(Talents.PremiereImpression, 2, false, null, null),
            new Talent(Talents.Riposte, 2, true, null, null),
            new Talent(Talents.ArmesJet, 3, false, null, null),
            new Talent(Talents.RireEncourageant, 3, false, null, null),
            new Talent(Talents.DonLangues, 4, false, null, null),
            new Talent(Talents.TissageMaitreArmes, 4, true, null, null),
            new Talent(Talents.DeuxiemeArme, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.SourireRavageur, 5, false, null, null),
            new Talent(Talents.Desarmement, 6, true, null, null),
            new Talent(Talents.Distraction, 6, false, null, null),
            new Talent(Talents.DeuxiemeAttaque, 7, true, null, null),
            new Talent(Talents.SangFroid, 7, true, null, null),
            new Talent(Talents.Anticipation, 8, false, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.SortieGracieuse, 8, false, null, null),
            new Talent(Talents.AttaqueAnnoncee, 9, true, null, null),
            new Talent(Talents.AttaqueCobra, 9, false, null, null),
            new Talent(Talents.ControleAdversaires, 9, true, null, null),
            new Talent(Talents.AttaqueCritique, 10, true, null, null),
            new Talent(Talents.AttaqueTornade, 10, true, null, null),
            new Talent(Talents.PerceArmure, 11, true, null, null),
            new Talent(Talents.ViveLame, 11, false, null, null),
            new Talent(Talents.DefenseAmelioree, 12, true, null, null),
            new Talent(Talents.UltimeSursaut, 12, false, null, null),
            new Talent(Talents.AttaqueAstrale, 13, false, null, null),
            new Talent(Talents.DefiChampion, 13, true, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.AttaqueMatrices, 14, false, null, null),
            new Talent(Talents.AttaqueMultiple, 14, true, null, null),
            new Talent(Talents.ArmeEtheree, 15, true, null, null),
            new Talent(Talents.AttaqueDecisive, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.CHA), 5),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 6),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.ArmesMelee), 7),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 8),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 10),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 10),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 11),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 13),
 			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 14),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 2), 15),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 2), 15))),

    MaitreAnimaux("Maitre des Animaux",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.Apprivoisement, 1, true, null, null),
            new Talent(Talents.Griffes, 1, true, null, null),
            new Talent(Talents.CombatMainsNues, 1, false, null, null),
            new Talent(Talents.DominationAnimaux, 1, true, null, null),
            new Talent(Talents.Pistage, 1, false, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 7, 6),
            new Talent(Talents.AnalyseCreature, 2, true, null, null),
            new Talent(Talents.Dressage, 2, true, null, null),
            new Talent(Talents.BondLezard, 3, true, null, null),
            new Talent(Talents.PatteVelours, 3, true, null, null),
            new Talent(Talents.RegardTerrifiantMaitre, 4, true, null, null), /* l'un OU */
            new Talent(Talents.SymboleAnimal, 4, true, null, null), /* l'autre */
            new Talent(Talents.TissageMaitreAnimaux, 4, true, null, null),
            new Talent(Talents.EmpruntSensoriel, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.SoinCompagnonAnimal, 5, true, null, null),
            new Talent(Talents.EnduranceFroid, 6, false, null, null),
            new Talent(Talents.AffolementTroupeaux, 6, true, null, null),
            new Talent(Talents.DechainementGriffes, 7, true, null, null),
            new Talent(Talents.DetectionPoison, 7, false, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.CoeurLion, 8, true, null, null),
            new Talent(Talents.ResistancePoison, 8, false, null, null),
            new Talent(Talents.ConstitutionBestiale, 9, false, null, null),
            new Talent(Talents.Hurlement, 9, true, null, null),
            new Talent(Talents.PossessionAnimal, 9, false, null, null),
            new Talent(Talents.CommandementAnimaux, 10, true, null, null),
            new Talent(Talents.EspritLion, 10, false, null, null), /* n'existe pas dans la liste de disciplines */
            new Talent(Talents.DressageMonture, 11, true, null, null), /* "domptage de monture" dans la liste des disciplines */
            new Talent(Talents.SensAnimal, 11, true, null, null),
            new Talent(Talents.Cameleon, 12, false, null, null),
            new Talent(Talents.RecuperationBestiale, 12, true, null, null),
            new Talent(Talents.DeuxiemeChance, 13, false, null, null),
            new Talent(Talents.Pietinement, 13, false, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.AttaqueAstrale, 14, false, null, null),
            new Talent(Talents.LocalisationEcho, 14, true, null, null),
            new Talent(Talents.ToileAstrale, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null),
            new Talent(Talents.Venin, 15, true, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.CHA), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.VOL), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.END), 6),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 7),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 8),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 13),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 14),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 15),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 2), 15))),

    NavigateurCiel("Navigateur du Ciel",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.AttaqueAcrobatique, 1, false, null, null),
            new Talent(Talents.Escalade, 1, true, null, null),
            new Talent(Talents.Esquive, 1, true, null, null),
            new Talent(Talents.NavigationAerienne, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 6, 5),
            new Talent(Talents.ArmesJet, 2, false, null, null),
            new Talent(Talents.SautGeant, 2, true, null, null),
            new Talent(Talents.ChutePlume, 3, true, null, null),
            new Talent(Talents.Stabilite, 3, true, null, null),
            new Talent(Talents.CombatMainsNues, 4, false, null, null),
            new Talent(Talents.TissageNavigateurCiel, 4, true, null, null),
            new Talent(Talents.DanseAirs, 5, false, new InitPreAction(Pointcuts.INIT), new InitPostAction(Pointcuts.INIT)),
            new Talent(Talents.Marchandage, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.Riposte, 6, false, null, null),
            new Talent(Talents.Sarcasmes, 6, false, null, null),
            new Talent(Talents.DeuxiemeArme, 7, false, null, null),
            new Talent(Talents.DonLangues, 7, true, null, null),
            new Talent(Talents.ArmesTir, 8, false, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.MarcheVents, 8, true, null, null),
            new Talent(Talents.CoeurLion, 9, true, null, null),
            new Talent(Talents.DeuxiemeAttaque, 9, false, null, null),
            new Talent(Talents.SangFroid, 9, true, null, null),
            new Talent(Talents.AttaqueBalancier, 10, false, null, null),
            new Talent(Talents.EnduranceFroid, 10, true, null, null),
            new Talent(Talents.DefenseAmelioree, 11, true, null, null), /* "défense" dans la liste des disciplines */
            new Talent(Talents.PerceArmure, 11, false, null, null), /* "Passe-bouclier" dans la liste des disciplines */
            new Talent(Talents.AttaqueCritique, 12, false, null, null),
            new Talent(Talents.UltimeSursaut, 12, true, null, null),
            new Talent(Talents.DestructionArme, 13, false, null, null),
            new Talent(Talents.DeuxiemeChance, 13, true, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.AttaqueMatrices, 14, false, null, null),
            new Talent(Talents.ViveLame, 14, false, null, null),
            new Talent(Talents.TirRapide, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null),
            new Talent(Talents.Vitalite, 15, true, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.STR), 5),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 6),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.ArmesMelee), 7),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 8),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 9),
            Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 13),
 			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 2), 15),
 			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 15))),

    Purificateur("Purificateur",
        Arrays.asList(new Talent(Talents.CombatMainsNues, 1, true, null, null),
            new Talent(Talents.ControleCorporel, 1, true, null, null),
            new Talent(Talents.CriGuerre, 1, false, null, null),
            new Talent(Talents.Enracinement, 1, true, null, null),
            new Talent(Talents.Esquive, 1, true, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.AnalyseCreature, 2, true, null, null),
            new Talent(Talents.DetectionVie, 2, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 7, 6),
            new Talent(Talents.LienTellurique, 3, false, null, null),
            new Talent(Talents.PeauArgile, 3, true, null, null),
            new Talent(Talents.LanguesElementaires, 4, true, null, null),
            new Talent(Talents.TissagePurificateur, 4, false, null, null),
            new Talent(Talents.CoupPiedRapide, 5, false, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.VolonteFer, 5, false, null, null),
            new Talent(Talents.UltimeSursaut, 6, true, null, null),
            new Talent(Talents.VivaciteTigre, 6, false, new InitPreAction(Pointcuts.INIT_MOD), new InitPostAction(Pointcuts.INIT_MOD)),
            new Talent(Talents.DeuxiemeAttaque, 7, true, null, null),
            new Talent(Talents.PeauTellurique, 7, false, null, null),
            new Talent(Talents.CoeurLion, 8, true, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.CoupDevastateur, 8, true, null, null),
            new Talent(Talents.AttaqueAstrale, 9, true, null, null),
            new Talent(Talents.AttaqueMatrices, 9, false, null, null),
            new Talent(Talents.RugissementGuerre, 9, false, null, null),
            new Talent(Talents.AbriVegetal, 10, true, null, null),
            new Talent(Talents.ConstitutionBestiale, 10, false, null, null),
            new Talent(Talents.DetectionDefautsArmure, 11, false, null, null),
            new Talent(Talents.Vitalite, 11, false, null, null),
            new Talent(Talents.ArmureTellurique, 12, true, null, null),
            new Talent(Talents.RecuperationBestiale, 12, false, null, null),
            new Talent(Talents.GuideElementaire, 13, true, null, null),
            new Talent(Talents.PeauPierre, 13, true, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.AttaqueDecisive, 14, false, null, null),
            new Talent(Talents.DeuxiemeChance, 14, false, null, null),
            new Talent(Talents.AttaqueTornade, 15, false, null, null),
            new Talent(Talents.AuraProtectrice, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 4))),

    Necromancien("Nécromancien",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.Incantation, 1, true, null, null),
            new Talent(Talents.LectureEcriture, 1, false, null, null),
            new Talent(Talents.LectureEcritureMagie, 1, true, null, null),
            new Talent(Talents.MatriceSort, 1, false, null, null),
            new Talent(Talents.MatriceSort, 1, false, null, null),
            new Talent(Talents.TissageNecromancien, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 4, 3),
            new Talent(Talents.RegardTerrifiant, 2, false, null, null),
            new Talent(Talents.VisionAstrale, 2, true, null, null),
            new Talent(Talents.LangueEsprits, 3, true, null, null),
            new Talent(Talents.MatriceSort, 3, false, null, null),
            new Talent(Talents.MatriceSort, 4, false, null, null),
            new Talent(Talents.PossessionAnimal, 4, false, null, null),
            new Talent(Talents.ImmobilisationEsprit, 5, true, null, null),
            new Talent(Talents.Invocation, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.DetectionVie, 6, true, null, null),
            new Talent(Talents.Determination, 6, false, null, null),
            new Talent(Talents.MatriceAmelioree, 7, false, null, null),
            new Talent(Talents.ParadeSpectrale, 7, true, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.EspritGuetteur, 8, true, null, null),
            new Talent(Talents.MatriceAmelioree, 8, false, null, null),
            new Talent(Talents.MarmonnementSibyllins, 9, false, null, null),
            new Talent(Talents.MatriceRenforcee, 9, false, null, null),
            new Talent(Talents.PocheAstrale, 9, true, null, null),
            new Talent(Talents.AnimationObjet, 10, false, null, null),
            new Talent(Talents.CercleInvocation, 10, true, null, null),
            new Talent(Talents.MatriceRenforcee, 11, false, null, null),
            new Talent(Talents.NegociationCreatureInvoquee, 11, true, null, null),
            new Talent(Talents.AttaqueMatrices, 12, true, null, null),
            new Talent(Talents.ProjectionAstrale, 12, true, null, null),
            new Talent(Talents.MatricePartagee, 13, false, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.VerrouCristallinSort, 13, true, null, null),
            new Talent(Talents.MatricePartagee, 14, false, null, null),
            new Talent(Talents.TissageMultiple, 14, true, null, null),
            new Talent(Talents.DestructionAme, 15, true, null, null),
            new Talent(Talents.MatricePartagee, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.VOL), 5),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 6),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 7),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, CreatureInvoquee), 8), // voir page 143 : karma sur action réalisée par créature invoquée
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.Incantation), 9),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 13),
			Perks.get(Mod.get(Pointcuts.INIT, 1), 13),
 			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 2), 14),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 15))),

    Sorcier("Sorcier",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.Incantation, 1, true, null, null),
            new Talent(Talents.LectureEcriture, 1, true, null, null),
            new Talent(Talents.LectureEcritureMagie, 1, true, null, null),
            new Talent(Talents.MatriceSort, 1, false, null, null),
            new Talent(Talents.MatriceSort, 1, false, null, null),
            new Talent(Talents.TissageSorcier, 1, false, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 4, 3),
            new Talent(Talents.AnalyseIndices, 2, true, null, null),
            new Talent(Talents.MatriceSort, 2, false, null, null),
            new Talent(Talents.MarmonnementSibyllins, 3, true, null, null),
            new Talent(Talents.MemoireLivresque, 3, true, null, null),
            new Talent(Talents.SouvenirsLivresques, 4, true, null, null),
            new Talent(Talents.VisionAstrale, 4, true, null, null),
            new Talent(Talents.Determination, 5, false, null, null),
            new Talent(Talents.LectureLevres, 5, false, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.DonLangues, 6, true, null, null),
            new Talent(Talents.MatriceAmelioree, 6, false, null, null),
            new Talent(Talents.DetectionVie, 7, true, null, null),
            new Talent(Talents.MaintienFilament, 7, true, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.MatriceAmelioree, 8, false, null, null),
            new Talent(Talents.SangFroid, 8, false, null, null),
            new Talent(Talents.AttaqueMatrices, 9, true, null, null),
            new Talent(Talents.ExtensionTrame, 9, true, null, null),
            new Talent(Talents.MatriceRenforcee, 9, false, null, null),
            new Talent(Talents.AttaqueAstrale, 10, true, null, null),
            new Talent(Talents.UltimeSursaut, 10, false, null, null),
            new Talent(Talents.MatriceRenforcee, 11, false, null, null),
            new Talent(Talents.TrameIncantation, 11, true, null, null),
            new Talent(Talents.MatriceRenforcee, 12, false, null, null),
            new Talent(Talents.TransfertBlessure, 12, true, null, null),
            new Talent(Talents.MatricePartagee, 13, false, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.VisionVeritable, 13, false, null, null),
            new Talent(Talents.EspritGuetteur, 14, true, null, null),
            new Talent(Talents.MatricePartagee, 14, false, null, null),
            new Talent(Talents.MatricePartagee, 15, false, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null),
            new Talent(Talents.TrameEffet, 15, true, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.VOL), 5),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 6),
			// XXX Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Damage.Incantation), 7),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 8),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 9),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 11),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 15),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 15),
            Perks.get(Mod.get(Pointcuts.INIT, 1), 15))),

    Troubadour("Troubadour",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.ChantEmouvant, 1, true, null, null),
            new Talent(Talents.DeguisementMagique, 1, true, null, null),
            new Talent(Talents.ImitationVoix, 1, true, null, null),
            new Talent(Talents.PremiereImpression, 1, false, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 6, 5),
            new Talent(Talents.DonLangues, 2, true, null, null),
            new Talent(Talents.HistoireObjets, 2, false, null, null),
            new Talent(Talents.LectureEcriture, 3, true, null, null),
            new Talent(Talents.SensEmpathique, 3, true, null, null),
            new Talent(Talents.Sarcasmes, 4, false, null, null),
            new Talent(Talents.TissageTroubadour, 4, true, null, null),
            new Talent(Talents.ArmesJet, 5, false, null, null),
            new Talent(Talents.Distraction, 5, true, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
            new Talent(Talents.Marchandage, 6, false, null, null),
            new Talent(Talents.SangFroid, 6, true, null, null),
            new Talent(Talents.ArmesTir, 7, false, null, null),
            new Talent(Talents.ManipulationFoules, 7, true, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.Hypnose, 8, false, null, null),
            new Talent(Talents.SortieGracieuse, 8, false, null, null),
            new Talent(Talents.BarriereLames, 9, false, null, null),
            new Talent(Talents.VisionVeritable, 9, false, null, null),
            new Talent(Talents.VoixBarde, 9, true, null, null),
            new Talent(Talents.Multilinguisme, 10, false, null, null),
            new Talent(Talents.RejetResponsabilite, 10, true, null, null),
            new Talent(Talents.ChantProtection, 11, true, null, null),
            new Talent(Talents.TirImpressionnant, 11, false, null, null),
            new Talent(Talents.LienTelepathique, 12, false, null, null),
            new Talent(Talents.Reconstitution, 12, true, null, null),
            new Talent(Talents.JugementSang, 13, false, null, null),
            new Talent(Talents.DetectionInfluence, 13, true, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.LangueEsprits, 14, false, null, null),
            new Talent(Talents.UltimeSursaut, 14, false, null, null),
            new Talent(Talents.AuraProtectrice, 15, false, null, null),
            new Talent(Talents.ConfrontationHorreur, 15, true, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 4),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.CHA), 6),
			// 7e cercle : jet de karma pour l'action sociale d'un autre perso (p. 157)
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 9),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 10),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
            Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 11),
            Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 12),
            Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 12),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
            Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 14),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 14),
            Perks.get(Mod.get(Pointcuts.DEF_MAG, 2), 15),
            Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 15))),

    Voleur("Voleur",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false, null, null),
            new Talent(Talents.RituelKarma, 1, false, null, null),
            new Talent(Talents.Crochetage, 1, true, null, null),
            new Talent(Talents.DeplacementSilencieux, 1, true, null, null),
            new Talent(Talents.Escalade, 1, false, null, null),
            new Talent(Talents.VolTire, 1, true, null, null),
            new Talent(Talents.Endurance, 2, false, null, null, 5, 4),
            new Talent(Talents.AttaqueSurprise, 2, true, null, null),
            new Talent(Talents.SensSerrures, 2, true, null, null),
            new Talent(Talents.Esquive, 3, true, null, null),
            new Talent(Talents.Recel, 3, true, null, null),
            new Talent(Talents.EsquivePieges, 4, true, null, null),
            new Talent(Talents.TissageVoleur, 4, true, null, null),
            new Talent(Talents.DesarmocagePieges, 5, true, null, null),
            new Talent(Talents.DetectionPieges, 5, false, null, null),
            new Talent(Talents.RituelMaitreFantome, 5, false, null, null),
            new Talent(Talents.DeguisementMagique, 6, false, null, null),
            new Talent(Talents.Escamotage, 6, true, null, null),
            new Talent(Talents.ArmesJet, 7, true, null, null),
            new Talent(Talents.DetectionArmes, 7, false, null, null),
            new Talent(Talents.ArmesTir, 8, false, null, null),
            new Talent(Talents.Commandement, 8, false, null, null),
            new Talent(Talents.RejetResponsabilite, 8, false, null, null),
            new Talent(Talents.DetectionOr, 9, false, null, null),
            new Talent(Talents.DissimulationArme, 9, true, null, null),
            new Talent(Talents.Sprint, 9, false, null, null),
            new Talent(Talents.DonLangues, 10, false, null, null),
            new Talent(Talents.PocheAstrale, 10, true, null, null),
            new Talent(Talents.LectureLevres, 11, true, null, null),
            new Talent(Talents.Stabilite, 11, false, null, null),
            new Talent(Talents.DetectionPoison, 12, true, null, null),
            new Talent(Talents.ViveLame, 12, false, null, null),
            new Talent(Talents.Cameleon, 13, false, null, null),
            new Talent(Talents.TirAvertissement, 13, false, null, null),
            new Talent(Talents.TramageTalent, 13, false, null, null),
            new Talent(Talents.DefenseAmelioree, 14, false, null, null),
            new Talent(Talents.Ricochet, 14, false, null, null),
            new Talent(Talents.ApprocheSurprise, 15, true, null, null),
            new Talent(Talents.TrameAttribut, 15, false, null, null),
            new Talent(Talents.VisionVeritable, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.PER), 5),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Attributs.DEX), 6),
			Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 7),
			Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 9),
			Perks.get(Mod.get(Pointcuts.KARMA_USE, 1, Pointcuts.RECOVERY_LVL), 9),
			Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 10),
            Perks.get(Mod.get(Pointcuts.RECOVERY_TESTS, 1), 10),
            Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 11),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 11),
            Perks.get(Mod.get(Pointcuts.DEF_SOC, 1), 12),
            Perks.get(Mod.get(Pointcuts.INIT, 1), 13),
			Perks.get(Mod.get(Pointcuts.KARMA_POINTS, 25), 13),
            Perks.get(Mod.get(Pointcuts.DEF_MAG, 1), 14),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 2), 14),
            Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 15))),

// NOUVELLES DISCIPLINES (SAUF PURIFICATEUR PLUS HAUT)

    Chaman("Chaman",
		Arrays.asList(new Talent(Talents.CreationFetiche, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.Incantation, 1, true, null, null),
			new Talent(Talents.FeticheSort, 1, false, null, null),
			new Talent(Talents.TissageChaman, 1, true, null, null),
			new Talent(Talents.Survie, 1, true, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.FeticheSort, 2, false, null, null),
			new Talent(Talents.VisionAstrale, 2, true, null, null),
			new Talent(Talents.LangueEsprits, 3, true, null, null),
			new Talent(Talents.MarmonnementSibyllins, 3, false, null, null),
			new Talent(Talents.FeticheSort, 4, false, null, null),
			new Talent(Talents.GuerisonFeu, 4, true, null, null),
			new Talent(Talents.ImmobilisationEsprit, 5, true, null, null),
			new Talent(Talents.Invocation, 5, true, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.Determination, 6, false, null, null),
			new Talent(Talents.SensEmpathique, 6, false, null, null),
			new Talent(Talents.DetectionVie, 7, false, null, null),
			new Talent(Talents.FeticheAmeliore, 7, true, null, null),
			new Talent(Talents.Commandement, 8, true, null, null),
			new Talent(Talents.FeticheAmeliore, 8, false, null, null),
			new Talent(Talents.GuideElementaire, 8, true, null, null),
			new Talent(Talents.EmpruntSensoriel, 9, true, null, null),
			new Talent(Talents.FeticheAmeliore, 9, false, null, null),
			new Talent(Talents.PatteVelours, 9, false, null, null),
			new Talent(Talents.AbriVegetal, 10, true, null, null),
			new Talent(Talents.RemodelageObjet, 10, false, null, null),
			new Talent(Talents.AnimationObjet, 11, true, null, null),
			new Talent(Talents.CercleInvocation, 11, true, null, null),
			new Talent(Talents.FeticheRenforce, 11, false, null, null),
			new Talent(Talents.FeticheRenforce, 12, false, null, null),
			new Talent(Talents.NegociationCreatureInvoquee, 12, true, null, null),
			new Talent(Talents.AttaqueMatrices, 13, true, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.VisionVeritable, 13, true, null, null),
			new Talent(Talents.EspritGuetteur, 14, true, null, null),
			new Talent(Talents.FetichePartage, 14, false, null, null),
			new Talent(Talents.FetichePartage, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null),
			new Talent(Talents.TissageMultiple, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

    ChasseurHorreurs("Chasseur d'Horreurs",
		Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.DeplacementSilencieux, 1, false, null, null),
			new Talent(Talents.Esquive, 1, true, null, null),
			new Talent(Talents.VisionAstrale, 1, false, null, null),
			new Talent(Talents.VolonteFer, 1, true, null, null),
			new Talent(Talents.AnalyseCreature, 2, true, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.Pistage, 2, true, null, null),
			new Talent(Talents.ContreMalediction, 3, true, null, null),
			new Talent(Talents.Quarantaine, 3, true, null, null),
			new Talent(Talents.RireEncourageant, 4, false, null, null),
			new Talent(Talents.TissageChasseurHorreurs, 4, true, null, null),
			new Talent(Talents.CoeurLion, 5, true, null, null),
			new Talent(Talents.Endurcissement, 5, true, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.UltimeSursaut, 6, true, null, null),
			new Talent(Talents.VivaciteTigre, 6, false, new InitPreAction(Pointcuts.INIT_MOD), new InitPostAction(Pointcuts.INIT_MOD)),
			new Talent(Talents.DeuxiemeAttaque, 7, true, null, null),
			new Talent(Talents.ParadeSpectrale, 7, true, null, null),
			new Talent(Talents.AttaqueAstrale, 8, true, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.RegardFroid, 8, false, null, null),
			new Talent(Talents.CoupDevastateur, 9, false, null, null),
			new Talent(Talents.RecuperationBestiale, 9, false, null, null),
			new Talent(Talents.VoixBarde, 9, false, null, null),
			new Talent(Talents.DefenseAmelioree, 10, false, null, null),
			new Talent(Talents.EspritLion, 10, false, null, null),
			new Talent(Talents.DetectionInfluence, 11, true, null, null),
			new Talent(Talents.Vitalite, 11, false, null, null),
			new Talent(Talents.Cameleon, 12, true, null, null),
			new Talent(Talents.ConfrontationHorreur, 12, true, null, null),
			new Talent(Talents.AuraProtectrice, 13, true, null, null),
			new Talent(Talents.DissipationInfluence, 13, false, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.AttaqueDecisive, 14, false, null, null),
			new Talent(Talents.DeuxiemeChance, 14, false, null, null),
			new Talent(Talents.AttaqueMultiple, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null),
			new Talent(Talents.ProjectionAstrale, 15, true, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	DanseurCaudal("Danseur caudal",
		Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
			new Talent(Talents.AttaqueAcrobatique, 1, false, null, null),
			new Talent(Talents.CombatMainsNues, 1, true, null, null),
			new Talent(Talents.Envolee, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.Sarcasmes, 1, false, null, null),
			new Talent(Talents.ArmesJet, 2, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.Esquive, 2, false, null, null),
			new Talent(Talents.DanseCaudale, 3, true, null, null),
			new Talent(Talents.DanseAirs, 3, false, new InitPreAction(Pointcuts.INIT), new InitPostAction(Pointcuts.INIT)),
			new Talent(Talents.Stabilite, 4, true, null, null),
			new Talent(Talents.TissageDanseurCaudal, 4, true, null, null),
			new Talent(Talents.DanseDistraction, 5, true, null, null),
			new Talent(Talents.Manoeuvre, 5, true, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.AttaqueEnchainee, 6, false, null, null),
			new Talent(Talents.BondLezard, 6, true, null, null),
			new Talent(Talents.DeuxiemeArme, 7, true, null, null),
			new Talent(Talents.UltimeSursaut, 7, false, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.Desarmement, 8, true, null, null),
			new Talent(Talents.SangFroid, 8, false, null, null),
			new Talent(Talents.AttaqueAnnoncee, 9, true, null, null),
			new Talent(Talents.CoeurLion, 9, false, null, null),
			new Talent(Talents.OeilAigle, 9, false, null, null),
			new Talent(Talents.ArmeCorporelle, 10, true, null, null),
			new Talent(Talents.AttaqueTornade, 10, false, null, null),
			new Talent(Talents.PerceArmure, 11, false, null, null),
			new Talent(Talents.ViveLame, 11, false, null, null),
			new Talent(Talents.BarriereLames, 12, false, null, null),
			new Talent(Talents.DefenseAmelioree, 12, true, null, null),
			new Talent(Talents.AttaqueAstrale, 13, false, null, null),
			new Talent(Talents.DefiChampion, 13, true, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.AttaqueMatrices, 14, false, null, null),
			new Talent(Talents.AttaqueMultiple, 14, true, null, null),
			new Talent(Talents.AttaqueDecisive, 15, true, null, null),
			new Talent(Talents.DeuxiemeChance, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	DanseurVent("Danseur du vent",
		Arrays.asList(new Talent(Talents.ArmesMelee, 1, false, null, null),
			new Talent(Talents.DonLangues, 1, false, null, null),
			new Talent(Talents.DanseVent, 1, true, null, null),
			new Talent(Talents.Eloquence, 1, true, null, null),
			new Talent(Talents.ImitationVoix, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.Etiquette, 2, true, null, null),
			new Talent(Talents.HistoireObjets, 2, true, null, null),
			new Talent(Talents.ChantEmouvant, 3, true, null, null),
			new Talent(Talents.SymboleAnimal, 3, true, null, null),
			new Talent(Talents.TissageDanseurVent, 4, true, null, null),
			new Talent(Talents.VolTire, 4, false, null, null),
			new Talent(Talents.CommunicationVolatile, 5, true, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.Sarcasmes, 5, false, null, null),
			new Talent(Talents.LectureLevres, 6, false, null, null),
			new Talent(Talents.Marchandage, 6, true, null, null),
			new Talent(Talents.CoeurLion, 7, false, null, null),
			new Talent(Talents.MortFeinte, 7, true, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.Escamotage, 8, true, null, null),
			new Talent(Talents.Hypnose, 8, true, null, null),
			new Talent(Talents.LangueEsprits, 9, false, null, null),
			new Talent(Talents.SortieGracieuse, 9, false, null, null),
			new Talent(Talents.VoixBarde, 9, true, null, null),
			new Talent(Talents.SangFroid, 10, false, null, null),
			new Talent(Talents.RejetResponsabilite, 10, true, null, null),
			new Talent(Talents.ChantProtection, 11, false, null, null),
			new Talent(Talents.DetectionMensonges, 11, true, null, null),
			new Talent(Talents.AttaqueAnnoncee, 12, false, null, null),
			new Talent(Talents.Reconstitution, 12, true, null, null),
			new Talent(Talents.DetectionInfluence, 13, true, null, null),
			new Talent(Talents.JugementSang, 13, false, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.Multilinguisme, 14, true, null, null),
			new Talent(Talents.VisionVeritable, 14, false, null, null),
			new Talent(Talents.DeuxiemeChance, 15, true, null, null),
			new Talent(Talents.LocalisationEcho, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null)),
		Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	EclaireurVent("Eclaireur du vent",
		Arrays.asList(new Talent(Talents.AnalyseIndices, 1, true, null, null),
			new Talent(Talents.ArmesTir, 1, false, null, null),
			new Talent(Talents.DanseAirs, 1, true, new InitPreAction(Pointcuts.INIT), new InitPostAction(Pointcuts.INIT)),
			new Talent(Talents.Esquive, 1, true, null, null),
			new Talent(Talents.Pistage, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.ArmesMelee, 2, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.Vigilance, 2, true, null, null),
			new Talent(Talents.AnalyseCreature, 3, true, null, null),
			new Talent(Talents.AttaqueSurprise, 3, false, null, null),
			new Talent(Talents.PistageOlfactif, 4, true, null, null),
			new Talent(Talents.TissageEclaireurVent, 4, true, null, null),
			new Talent(Talents.EsquivePieges, 5, true, null, null),
			new Talent(Talents.PossessionAnimal, 5, false, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.DonLangues, 6, true, null, null),
			new Talent(Talents.OeilAigle, 6, false, null, null),
			new Talent(Talents.Anticipation, 7, true, null, null),
			new Talent(Talents.EnduranceFroid, 7, true, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.CommunicationVolatile, 8, true, null, null),
			new Talent(Talents.DetectionDefautsArmure, 8, false, null, null),
			new Talent(Talents.DetectionDanger, 9, true, null, null),
			new Talent(Talents.RecuperationBestiale, 9, false, null, null),
			new Talent(Talents.VisionVeritable, 9, true, null, null),
			new Talent(Talents.Cameleon, 10, true, null, null),
			new Talent(Talents.LocalisationTireur, 10, false, null, null),
			new Talent(Talents.DeviationProjectiles, 11, false, null, null),
			new Talent(Talents.GuideElementaire, 11, true, null, null),
			new Talent(Talents.DefenseAmelioree, 12, true, null, null),
			new Talent(Talents.EspritLion, 12, true, null, null),
			new Talent(Talents.LocalisationEcho, 13, true, null, null),
			new Talent(Talents.TirAveugle, 13, false, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.DetectionInfluence, 14, false, null, null),
			new Talent(Talents.DeuxiemeChance, 14, true, null, null),
			new Talent(Talents.ApprocheSurprise, 15, true, null, null),
			new Talent(Talents.TirMultiple, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	EruditExplorateur("Erudit explorateur",
		Arrays.asList(new Talent(Talents.AnalyseIndices, 1, false, null, null),
			new Talent(Talents.DonLangues, 1, true, null, null),
			new Talent(Talents.HistoireObjets, 1, true, null, null),
			new Talent(Talents.LectureEcriture, 1, true, null, null),
			new Talent(Talents.Recherche, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.ArmesMelee, 2, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.MemoireLivresque, 2, true, null, null),
			new Talent(Talents.Vigilance, 3, true, null, null),
			new Talent(Talents.VisionAstrale, 3, false, null, null),
			new Talent(Talents.Esquive, 4, false, null, null),
			new Talent(Talents.TissageEruditExplorateur, 4, true, null, null),
			new Talent(Talents.MarmonnementSibyllins, 5, false, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.SouvenirsLivresques, 5, true, null, null),
			new Talent(Talents.Distraction, 6, true, null, null),
			new Talent(Talents.SortieGracieuse, 6, true, null, null),
			new Talent(Talents.CoeurLion, 7, false, null, null),
			new Talent(Talents.LectureLevres, 7, true, null, null),
			new Talent(Talents.AnalyseCreature, 8, false, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.ImpressionDurable, 8, true, null, null),
			new Talent(Talents.Diplomatie, 9, false, null, null),
			new Talent(Talents.Hypnose, 9, true, null, null),
			new Talent(Talents.SangFroid, 9, false, null, null),
			new Talent(Talents.DetectionMensonges, 10, true, null, null),
			new Talent(Talents.VisionVeritable, 10, true, null, null),
			new Talent(Talents.Reconstitution, 11, true, null, null),
			new Talent(Talents.EspritLion, 11, false, null, null),
			new Talent(Talents.GuideElementaire, 12, true, null, null),
			new Talent(Talents.VoixBarde, 12, true, null, null),
			new Talent(Talents.OndeMentale, 13, true, null, null),
			new Talent(Talents.PenseeSecrete, 13, true, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.DetectionInfluence, 14, true, null, null),
			new Talent(Talents.DeuxiemeChance, 14, false, null, null),
			new Talent(Talents.Multilinguisme, 15, true, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null),
			new Talent(Talents.Vitalite, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	GardienBois("Gardien des bois",
		Arrays.asList(new Talent(Talents.ArmesTir, 1, false, null, null),
			new Talent(Talents.Escalade, 1, true, null, null),
			new Talent(Talents.Esquive, 1, true, null, null),
			new Talent(Talents.PatteVelours, 1, true, null, null),
			new Talent(Talents.Pistage, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.ArmesMelee, 2, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.MarqueMystique, 2, false, null, null),
			new Talent(Talents.Sprint, 3, false, null, null),
			new Talent(Talents.Stabilite, 3, true, null, null),
			new Talent(Talents.PeauBois, 4, false, null, new TempModAction(Pointcuts.HEALTH_POINTS, Pointcuts.UNCOUNSCIOUSNESS_THRESHOLD)),
			new Talent(Talents.TissageGardienBois, 4, true, null, null),
			new Talent(Talents.AnalyseCreature, 5, true, null, null),
			new Talent(Talents.Anticipation, 5, false, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.BondLezard, 6, true, null, null),
			new Talent(Talents.VivaciteTigre, 6, false, new InitPreAction(Pointcuts.INIT_MOD), new InitPostAction(Pointcuts.INIT_MOD)),
			new Talent(Talents.DominationAnimaux, 7, true, null, null),
			new Talent(Talents.EnduranceFroid, 7, true, null, null),
			new Talent(Talents.CoeurLion, 8, false, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.DetectionArmes, 8, true, null, null),
			new Talent(Talents.DetectionDanger, 9, true, null, null),
			new Talent(Talents.DeuxiemeAttaque, 9, false, null, null),
			new Talent(Talents.FlecheTracante, 9, true, null, null),
			new Talent(Talents.Cameleon, 10, true, null, null),
			new Talent(Talents.LocalisationTireur, 10, true, null, null),
			new Talent(Talents.AttaqueCritique, 11, false, null, null),
			new Talent(Talents.CommunicationSylvestre, 11, true, null, null),
			new Talent(Talents.DetectionDefautsArmure, 12, false, null, null),
			new Talent(Talents.TirImpressionnant, 12, true, null, null),
			new Talent(Talents.DefenseAmelioree, 13, false, null, null),
			new Talent(Talents.GuideElementaire, 13, true, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.AttaqueAstrale, 14, false, null, null),
			new Talent(Talents.DeuxiemeChance, 14, false, null, null),
			new Talent(Talents.ArmeEtheree, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null),
			new Talent(Talents.TransportSylvestre, 15, true, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	GuerrierBanni("Guerrier banni",
		Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
			new Talent(Talents.CombatMainsNues, 1, true, null, null),
			new Talent(Talents.CriGuerre, 1, true, null, null),
			new Talent(Talents.Esquive, 1, true, null, null),
			new Talent(Talents.PeauBois, 1, true, null, new TempModAction(Pointcuts.HEALTH_POINTS, Pointcuts.UNCOUNSCIOUSNESS_THRESHOLD)),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.Anticipation, 2, true, null, null),
			new Talent(Talents.CoupBouclier, 2, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.ArmesJet, 3, false, null, null),
			new Talent(Talents.VivaciteTigre, 3, false, new InitPreAction(Pointcuts.INIT_MOD), new InitPostAction(Pointcuts.INIT_MOD)),
			new Talent(Talents.AttaquePlongeante, 4, true, null, null),
			new Talent(Talents.TissageGuerrierBanni, 4, true, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.SangFeu, 5, true, null, null),
			new Talent(Talents.SautGeant, 5, false, null, null),
			new Talent(Talents.Sarcasmes, 6, false, null, null),
			new Talent(Talents.UltimeSursaut, 6, true, null, null),
			new Talent(Talents.PeauTellurique, 7, false, null, null),
			new Talent(Talents.RegardFroid, 7, true, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.DeuxiemeAttaque, 8, false, null, null),
			new Talent(Talents.SangFroid, 8, false, null, null),
			new Talent(Talents.CoeurLion, 9, true, null, null),
			new Talent(Talents.DeviationProjectiles, 9, false, null, null),
			new Talent(Talents.RugissementGuerre, 9, false, null, null),
			new Talent(Talents.ArmeCorporelle, 10, true, null, null),
			new Talent(Talents.AttaqueMatrices, 10, false, null, null),
			new Talent(Talents.DetectionDefautsArmure, 11, false, null, null),
			new Talent(Talents.Vitalite, 11, false, null, null),
			new Talent(Talents.Cameleon, 12, false, null, null),
			new Talent(Talents.DestructionArme, 12, true, null, null),
			new Talent(Talents.GuideElementaire, 13, false, null, null),
			new Talent(Talents.PeauPierre, 13, true, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.AttaqueDecisive, 14, false, null, null),
			new Talent(Talents.DeuxiemeChance, 14, false, null, null),
			new Talent(Talents.AttaqueMultiple, 15, true, null, null),
			new Talent(Talents.AuraProtectrice, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	Liberateur("Libérateur",
		Arrays.asList(new Talent(Talents.CombatMainsNues, 1, true, null, null),
			new Talent(Talents.Crochetage, 1, true, null, null),
			new Talent(Talents.DetectionLiberte, 1, true, null, null),
			new Talent(Talents.Esquive, 1, true, null, null),
			new Talent(Talents.Evasion, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.ArmesMelee, 2, true, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.EspritLibre, 2, true, null, null),
			new Talent(Talents.CriJustice, 3, true, null, null),
			new Talent(Talents.PulsionLiberte, 3, false, null, null),
			new Talent(Talents.ArmesJet, 4, false, null, null),
			new Talent(Talents.TissageLiberateur, 4, true, null, null),
			new Talent(Talents.Anticipation, 5, true, null, null),
			new Talent(Talents.MenottesFictives, 5, true, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.EspritLion, 6, true, null, null),
			new Talent(Talents.MortFeinte, 6, false, null, null),
			new Talent(Talents.ArmeSpirituelle, 7, true, null, null),
			new Talent(Talents.GuerisonEsclaves, 7, true, null, null),
			new Talent(Talents.Commandement, 8, true, null, null),
			new Talent(Talents.DeguisementAstral, 8, true, null, null),
			new Talent(Talents.DeuxiemeAttaque, 8, false, null, null),
			new Talent(Talents.ArmureSpirituelle, 9, true, null, null),
			new Talent(Talents.CoupPourCoup, 9, true, null, null),
			new Talent(Talents.ManipulationFoules, 9, false, null, null),
			new Talent(Talents.AugureEvasion, 10, true, null, null),
			new Talent(Talents.DetectionPrisonniers, 10, true, null, null),
			new Talent(Talents.DefiChampion, 11, false, null, null),
			new Talent(Talents.DetectionDefautsArmure, 11, false, null, null),
			new Talent(Talents.DiscretionImpossible, 12, false, null, null),
			new Talent(Talents.UltimeSursaut, 12, true, null, null),
			new Talent(Talents.DeuxiemeChance, 13, false, null, null),
			new Talent(Talents.GuideElementaire, 13, false, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.AttaqueDecisive, 14, false, null, null),
			new Talent(Talents.AttaqueMatrices, 14, false, null, null),
			new Talent(Talents.AttaqueMultiple, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null),
			new Talent(Talents.Vitalite, 15, true, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	MaitreVent("Maître du vent",
		Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
			new Talent(Talents.AttaquePlongeante, 1, true, null, null),
			new Talent(Talents.CombatMainsNues, 1, false, null, null),
			new Talent(Talents.Esquive, 1, true, null, null),
			new Talent(Talents.PeauBois, 1, true, null, new TempModAction(Pointcuts.HEALTH_POINTS, Pointcuts.UNCOUNSCIOUSNESS_THRESHOLD)),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.Anticipation, 2, true, null, null),
			new Talent(Talents.ArmesJet, 2, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.Sarcasmes, 3, false, null, null),
			new Talent(Talents.VivaciteTigre, 3, false, new InitPreAction(Pointcuts.INIT_MOD), new InitPostAction(Pointcuts.INIT_MOD)),
			new Talent(Talents.Bourdonnement, 4, true, null, null),
			new Talent(Talents.TissageMaitreVent, 4, true, null, null),
			new Talent(Talents.DetectionArmes, 5, false, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.VolArrache, 5, true, null, null),
			new Talent(Talents.Desarmement, 6, false, null, null),
			new Talent(Talents.UltimeSursaut, 6, true, null, null),
			new Talent(Talents.DeuxiemeAttaque, 7, true, null, null),
			new Talent(Talents.PeauTellurique, 7, false, null, null),
			new Talent(Talents.AttaqueAstrale, 8, true, null, null),
			new Talent(Talents.AttaqueEnchainee, 8, true, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.AttaqueCritique, 9, false, null, null),
			new Talent(Talents.DeuxiemeArme, 9, true, null, null),
			new Talent(Talents.DeviationProjectiles, 9, false, null, null),
			new Talent(Talents.AttaqueAnnoncee, 10, false, null, null),
			new Talent(Talents.AttaqueMatrices, 10, false, null, null),
			new Talent(Talents.DetectionDefautsArmure, 11, true, null, null),
			new Talent(Talents.Vitalite, 11, false, null, null),
			new Talent(Talents.ApprocheSurprise, 12, true, null, null),
			new Talent(Talents.Cameleon, 12, false, null, null),
			new Talent(Talents.GuideElementaire, 13, false, null, null),
			new Talent(Talents.PeauPierre, 13, true, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.AttaqueDecisive, 14, false, null, null),
			new Talent(Talents.DeuxiemeChance, 14, false, null, null),
			new Talent(Talents.AttaqueTornade, 15, true, null, null),
			new Talent(Talents.AuraProtectrice, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	Menestrel("Ménestrel",
		Arrays.asList(new Talent(Talents.ArmesMelee, 1, false, null, null),
			new Talent(Talents.DonLangues, 1, true, null, null),
			new Talent(Talents.Esquive, 1, false, null, null),
			new Talent(Talents.Performance, 1, true, null, null),
			new Talent(Talents.PremiereImpression, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.PerfectionnementLame, 2, true, null, null),
			new Talent(Talents.HistoireArmes, 2, true, null, null),
			new Talent(Talents.LectureEcriture, 3, false, null, null),
			new Talent(Talents.Marchandage, 3, true, null, null),
			new Talent(Talents.SymboleAnimal, 4, false, null, null),
			new Talent(Talents.TissageMenestrel, 4, true, null, null),
			new Talent(Talents.HistoireObjets, 5, true, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.SourireRavageur, 5, true, null, null),
			new Talent(Talents.ContreMalediction, 6, false, null, null),
			new Talent(Talents.SangFroid, 6, true, null, null),
			new Talent(Talents.DeguisementMagique, 7, true, null, null),
			new Talent(Talents.ImitationVoix, 7, true, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.DetectionArmes, 8, true, null, null),
			new Talent(Talents.VisionVeritable, 8, true, null, null),
			new Talent(Talents.AttaqueAnnoncee, 9, false, null, null),
			new Talent(Talents.ImpressionDurable, 9, true, null, null),
			new Talent(Talents.VoixBarde, 9, true, null, null),
			new Talent(Talents.DissimulationArme, 10, false, null, null),
			new Talent(Talents.RejetResponsabilite, 10, true, null, null),
			new Talent(Talents.MemoireImages, 11, true, null, null),
			new Talent(Talents.UltimeSursaut, 11, false, null, null),
			new Talent(Talents.PenseeSecrete, 12, true, null, null),
			new Talent(Talents.PerfectionnementArmure, 12, false, null, null),
			new Talent(Talents.LangueEsprits, 13, false, null, null),
			new Talent(Talents.LienTelepathique, 13, false, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.DeuxiemeChance, 14, false, null, null),
			new Talent(Talents.PremierCerclePerfection, 14, true, null, null),
			new Talent(Talents.Multilinguisme, 15, true, null, null),
			new Talent(Talents.PocheAstrale, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	Messager("Messager",
		Arrays.asList(new Talent(Talents.ArmesMelee, 1, false, null, null),
			new Talent(Talents.DetectionDirection, 1, true, null, null),
			new Talent(Talents.DonLangues, 1, true, null, null),
			new Talent(Talents.Escalade, 1, true, null, null),
			new Talent(Talents.Esquive, 1, false, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.LectureEcriture, 2, true, null, null),
			new Talent(Talents.Stabilite, 2, false, null, null),
			new Talent(Talents.Sprint, 3, true, null, null),
			new Talent(Talents.MemoireLivresque, 3, true, null, null),
			new Talent(Talents.SouvenirsLivresques, 4, false, null, null),
			new Talent(Talents.TissageMessager, 4, true, null, null),
			new Talent(Talents.Endurcissement, 5, true, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.SautGeant, 5, false, null, null),
			new Talent(Talents.DetectionPieges, 6, true, null, null),
			new Talent(Talents.EsquivePieges, 6, true, null, null),
			new Talent(Talents.EnduranceFroid, 7, true, null, null),
			new Talent(Talents.MarcheVents, 7, true, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.DetectionDanger, 8, true, null, null),
			new Talent(Talents.LangageVent, 8, true, null, null),
			new Talent(Talents.CoeurLion, 9, true, null, null),
			new Talent(Talents.DetectionArmes, 9, false, null, null),
			new Talent(Talents.MontureSpectrale, 9, false, null, null),
			new Talent(Talents.GuideElementaire, 10, true, null, null),
			new Talent(Talents.PenseeSecrete, 10, true, null, null),
			new Talent(Talents.SangFroid, 11, true, null, null),
			new Talent(Talents.VolonteFer, 11, true, null, null),
			new Talent(Talents.DeviationProjectiles, 12, true, null, null),
			new Talent(Talents.UltimeSursaut, 12, true, null, null),
			new Talent(Talents.DefenseAmelioree, 13, false, null, null),
			new Talent(Talents.DetectionPoison, 13, true, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.DeuxiemeChance, 14, true, null, null),
			new Talent(Talents.ResistancePoison, 14, false, null, null),
			new Talent(Talents.LocalisationEcho, 15, true, null, null),
			new Talent(Talents.PeauPierre, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1))),

	SoldatFleuve("Soldat du fleuve",
		Arrays.asList(new Talent(Talents.ArmesMelee, 1, true, null, null),
			new Talent(Talents.Escalade, 1, false, null, null),
			new Talent(Talents.Esquive, 1, true, null, null),
			new Talent(Talents.Natation, 1, true, null, null),
			new Talent(Talents.PilotageNavire, 1, true, null, null),
			new Talent(Talents.RituelKarma, 1, false, null, null),
			new Talent(Talents.ArmesJet, 2, false, null, null),
			new Talent(Talents.Endurance, 2, false, null, null),
			new Talent(Talents.FiletProtection, 2, true, null, null),
			new Talent(Talents.Marchandage, 3, true, null, null),
			new Talent(Talents.Stabilite, 3, true, null, null),
			new Talent(Talents.CombatMainsNues, 4, false, null, null),
			new Talent(Talents.TissageSoldatFleuve, 4, true, null, null),
			new Talent(Talents.AttaqueAcrobatique, 5, true, null, null),
			new Talent(Talents.Evaluation, 5, false, null, null),
			new Talent(Talents.RituelMaitreFantome, 5, true, null, null),
			new Talent(Talents.Distraction, 6, true, null, null),
			new Talent(Talents.DonLangues, 6, true, null, null),
			new Talent(Talents.DeuxiemeArme, 7, true, null, null),
			new Talent(Talents.RireEncourageant, 7, false, null, null),
			new Talent(Talents.ArmesTir, 8, false, null, null),
			new Talent(Talents.Commandement, 8, false, null, null),
			new Talent(Talents.SautGeant, 8, false, null, null),
			new Talent(Talents.CoeurLion, 9, true, null, null),
			new Talent(Talents.Desarmement, 9, false, null, null),
			new Talent(Talents.DeuxiemeAttaque, 9, false, null, null),
			new Talent(Talents.AttaqueBalancier, 10, true, null, null),
			new Talent(Talents.DetectionMensonges, 10, false, null, null),
			new Talent(Talents.DefenseAmelioree, 11, true, null, null),
			new Talent(Talents.PerceArmure, 11, false, null, null),
			new Talent(Talents.CoupDevastateur, 12, false, null, null),
			new Talent(Talents.UltimeSursaut, 12, true, null, null),
			new Talent(Talents.AttaqueTornade, 13, false, null, null),
			new Talent(Talents.DeuxiemeChance, 13, true, null, null),
			new Talent(Talents.TramageTalent, 13, false, null, null),
			new Talent(Talents.AttaqueMatrices, 14, false, null, null),
			new Talent(Talents.ViveLame, 14, false, null, null),
			new Talent(Talents.TirRapide, 15, false, null, null),
			new Talent(Talents.TrameAttribut, 15, false, null, null),
			new Talent(Talents.Vitalite, 15, true, null, null)),
        Arrays.asList(Perks.get(Mod.get(Pointcuts.DEF_PHY, 1), 1)));

    private String label;
    private List<Talent> talents;
    private List<Perks> bonuses;

    private Disciplines(final String aLabel, final List<Talent> someTalents, final List<Perks> someBonuses)
    {
        this.label = aLabel;
        this.talents = someTalents;
        this.bonuses = someBonuses;
    }

    /**
     * @return the label
     */
    public String getLabel()
    {
        return label;
    }

    /**
     * @return the talents
     */
    public List<Talent> getTalents()
    {
        return talents;
    }

    /**
     * @return the bonuses
     */
    public List<Perks> getBonuses()
    {
        return bonuses;
    }
}
