/**
 *
 */
package fr.android.earthdawn.character.enums;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

/**
 * @author DrMabulle
 *
 */
public enum Disciplines implements Serializable
{
    Archer("Archer",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.ArmesTir, 1, true), /* "armes de trait" dans la liste de disciplines */
            new Talent(Talents.Esquive, 1, false),
            new Talent(Talents.FlecheDirection, 1, true),
            new Talent(Talents.MarqueMystique, 1, true),
            new Talent(Talents.TirInfaillible, 1, true),
            new Talent(Talents.Endurance, 2, false, 6, 5),
            new Talent(Talents.ArmesJet, 2, true),
            new Talent(Talents.Sprint, 2, false),
            new Talent(Talents.FlecheEnflammee, 3, true),
            new Talent(Talents.Stabilite, 3, false),
            new Talent(Talents.ArmesMelee, 4, false),
            new Talent(Talents.TissageArcher, 4, true),
            new Talent(Talents.MarqueParalysante, 5, true), /* "immobilisation de la cible" dans la liste des disciplines */
            new Talent(Talents.PremiereImpression, 5, false),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.DonLangues, 6, false),
            new Talent(Talents.Ricochet, 6, true),
            new Talent(Talents.Anticipation, 7, false),
            new Talent(Talents.RappelFleches, 7, true),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.OeilAigle, 8, true),
            new Talent(Talents.DeuxiemeAttaque, 8, true),
            new Talent(Talents.DeplacementSilencieux, 9, false),
            new Talent(Talents.LocalisationTireur, 9, true),
            new Talent(Talents.TirImpressionnant, 9, true),
            new Talent(Talents.AttaqueCourse, 10, true),
            new Talent(Talents.TirAvertissement, 10, true),
            new Talent(Talents.TirAveugle, 11, true),
            new Talent(Talents.DominationFleches, 11, true), /* "tir rapide" dans le bouquin, corrigé en "domination des flèches" en erratum */
            new Talent(Talents.CreationFleches, 12, true),
            new Talent(Talents.DetectionDefautsArmure, 12, false),
            new Talent(Talents.DefenseAmelioree, 13, false), /*simplement "défense" dans le bouquin */
            new Talent(Talents.FlecheHurlante, 13, true),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.DeuxiemeChance, 14, false),
            new Talent(Talents.TirMultiple, 14, true),
            new Talent(Talents.ArcVent, 15, false),
            new Talent(Talents.ArmeEtheree, 15, true),
            new Talent(Talents.TrameAttribut, 15, false))),

    Cavalier("Cavalier",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.AcrobatiesEnSelle, 1, true),
            new Talent(Talents.Apprivoisement, 1, false),
            new Talent(Talents.Esquive, 1, false),
            new Talent(Talents.ChargeDevastatrice, 1, true),
            new Talent(Talents.Endurance, 2, false, 7, 6),
            new Talent(Talents.OrdreEmpathique, 2, true),
            new Talent(Talents.PartageSang, 2, true),
            new Talent(Talents.AttaqueTournoyante, 3, false),
            new Talent(Talents.MontureSpectrale, 3, true),
            new Talent(Talents.SangFroid, 4, true),
            new Talent(Talents.TissageCavalier, 4, true),
            new Talent(Talents.DefenseTournoyante, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.TenueSelle, 5, true),
            new Talent(Talents.DominationAnimaux, 6, false),
            new Talent(Talents.EnduranceMonture, 6, false),
            new Talent(Talents.ArmesTir, 7, false), /* "armes de trait" dans la liste de disciplines */
            new Talent(Talents.ImpressionDurable, 7, false),
            new Talent(Talents.ChargeTerrifiante, 8, true),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.Pietinement, 8, true),
            new Talent(Talents.AppelMonture, 9, true),
            new Talent(Talents.AttaquePlongeante, 9, false),
            new Talent(Talents.Ralliement, 9, true),
            new Talent(Talents.DefiChampion, 10, false),
            new Talent(Talents.ProtectionMonture, 10, false),
            new Talent(Talents.DressageMonture, 11, false), /* "domptage de monture" dans la liste de discipline */
            new Talent(Talents.SoinCompagnonAnimal, 11, true),
            new Talent(Talents.AttaqueEnchainee, 12, false),
            new Talent(Talents.RegardTerrifiantMaitre, 12, true),
            new Talent(Talents.PerceArmure, 13, true), /* "passe-bouclier" dans la liste des disciplines */
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.UltimeSursaut, 13, false),
            new Talent(Talents.DetectionDefautsArmure, 14, false),
            new Talent(Talents.MontureAgressive, 14, true),
            new Talent(Talents.ArmeEtheree, 15, false),
            new Talent(Talents.ChargeMultiple, 15, true),
            new Talent(Talents.TrameAttribut, 15, false))),

    Eclaireur("Eclaireur",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.DeplacementSilencieux, 1, true),
            new Talent(Talents.Escalade, 1, true),
            new Talent(Talents.Esquive, 1, true),
            new Talent(Talents.Pistage, 1, true),
            new Talent(Talents.Endurance, 2, false, 6, 5),
            new Talent(Talents.LectureEcriture, 2, false),
            new Talent(Talents.Manoeuvre, 2, false),
            new Talent(Talents.Sprint, 3, false),
            new Talent(Talents.VisionAstrale, 3, true),
            new Talent(Talents.Riposte, 4, false),
            new Talent(Talents.TissageEclaireur, 4, true),
            new Talent(Talents.EsquivePieges, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.SensSerrures, 5, false),
            new Talent(Talents.DonLangues, 6, false),
            new Talent(Talents.SautGeant, 6, false),
            new Talent(Talents.DetectionPieges, 7, true),
            new Talent(Talents.EnduranceFroid, 7, true),
            new Talent(Talents.ArmesTir, 8, false),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.MarcheVents, 8, true),
            new Talent(Talents.AnalyseCreature, 9, true),
            new Talent(Talents.Anticipation, 9, false),
            new Talent(Talents.DetectionArmes, 9, true),
            new Talent(Talents.DeviationProjectiles, 10, false),
            new Talent(Talents.LocalisationTireur, 10, true),
            new Talent(Talents.DeguisementMagique, 11, false),
            new Talent(Talents.Stabilite, 11, false),
            new Talent(Talents.DefenseAmelioree, 12, true),
            new Talent(Talents.ViveLame, 12, false),
            new Talent(Talents.DetectionPoison, 13, true),
            new Talent(Talents.GuideElementaire, 13, true),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.DeuxiemeChance, 14, false),
            new Talent(Talents.ResistancePoison, 14, true),
            new Talent(Talents.ArmeEtheree, 15, false),
            new Talent(Talents.LocalisationEcho, 15, true),
            new Talent(Talents.TrameAttribut, 15, false))),

    EcumeurCiel("Ecumeur du Ciel",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, true),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.CriGuerre, 1, true),
            new Talent(Talents.Esquive, 1, false),
            new Talent(Talents.NavigationAerienne, 1, true),
            new Talent(Talents.SangFeu, 1, true),
            new Talent(Talents.Endurance, 2, false, 8, 6),
            new Talent(Talents.CoupBouclier, 2, true),
            new Talent(Talents.SautGeant, 2, true),
            new Talent(Talents.ChutePlume, 3, true),
            new Talent(Talents.CombatMainsNues, 3, false),
            new Talent(Talents.CoupPiedRapide, 4, false),
            new Talent(Talents.TissageEcumeurCiel, 4, true),
            new Talent(Talents.Recel, 5, false),
            new Talent(Talents.RugissementGuerre, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.AttaqueEnchainee, 6, true),
            new Talent(Talents.RegardFroid, 6, true),
            new Talent(Talents.ArmesJet, 7, false),
            new Talent(Talents.DonLangues, 7, false),
            new Talent(Talents.ArmesTir, 8, false),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.CoupDevastateur, 8, true),
            new Talent(Talents.CoeurLion, 9, true),
            new Talent(Talents.DeuxiemeAttaque, 9, true),
            new Talent(Talents.EnduranceFroid, 9, true),
            new Talent(Talents.HacheTonnerre, 10, true),
            new Talent(Talents.PerceArmure, 10, false),
            new Talent(Talents.DefenseAmelioree, 11, false),
            new Talent(Talents.DestructionArme, 11, true),
            new Talent(Talents.AttaqueCritique, 12, false),
            new Talent(Talents.Vitalite, 12, false),
            new Talent(Talents.AttaqueMatrices, 13, false),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.ViveLame, 13, false),
            new Talent(Talents.Hurlement, 14, false),
            new Talent(Talents.TirRapide, 14, false),
            new Talent(Talents.FlecheHurlante, 15, false),
            new Talent(Talents.PeauPierre, 15, true),
            new Talent(Talents.TrameAttribut, 15, false))),

    Elementaliste("Elémentaliste",
        Arrays.asList(new Talent(Talents.Incantation, 1, true),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.LectureEcriture, 1, false),
            new Talent(Talents.LectureEcritureMagie, 1, false),
            new Talent(Talents.MatriceSort, 1, false),
            new Talent(Talents.MatriceSort, 1, false),
            new Talent(Talents.TissageElementaliste, 1, true),
            new Talent(Talents.Endurance, 2, false, 4, 3),
            new Talent(Talents.GuerisonFeu, 2, true),
            new Talent(Talents.MatriceSort, 2, false),
            new Talent(Talents.LangageVent, 3, true),
            new Talent(Talents.LanguesElementaires, 3, true),
            new Talent(Talents.MatriceSort, 4, false),
            new Talent(Talents.VisionAstrale, 4, false),
            new Talent(Talents.ImmobilisationElementaire, 5, true),
            new Talent(Talents.Invocation, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.Determination, 6, false),
            new Talent(Talents.PurificationFroid, 6, true),
            new Talent(Talents.Enracinement, 7, false),
            new Talent(Talents.MatriceAmelioree, 7, false),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.ControleTemperature, 8, true),
            new Talent(Talents.MatriceAmelioree, 8, false),
            new Talent(Talents.GuideElementaire, 9, true),
            new Talent(Talents.MatriceRenforcee, 9, false),
            new Talent(Talents.ProtectionContreMetal, 9, true),
            new Talent(Talents.AbriVegetal, 10, true),
            new Talent(Talents.RemodelageObjet, 10, true),
            new Talent(Talents.AnimationObjet, 11, false),
            new Talent(Talents.CercleInvocation, 11, true),
            new Talent(Talents.MatriceRenforcee, 12, false),
            new Talent(Talents.NegociationCreatureInvoquee, 12, true),
            new Talent(Talents.DanseEaux, 13, true),
            new Talent(Talents.TerreFlottante, 13, true), /* "terre mouvante" dans la liste des disciplines */
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.ArmureTellurique, 14, true),
            new Talent(Talents.MatricePartagee, 14, false),
            new Talent(Talents.MaintienFilament, 15, false),
            new Talent(Talents.MatricePartagee, 15, false),
            new Talent(Talents.TrameAttribut, 15, false))),

    Forgeron("Forgeron",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.ArmesMelee, 1, false),
            new Talent(Talents.Esquive, 1, false),
            new Talent(Talents.HistoireArmes, 1, true),
            new Talent(Talents.PerfectionnementLame, 1, true),
            new Talent(Talents.VolonteFer, 1, true),
            new Talent(Talents.Endurance, 2, false, 6, 5),
            new Talent(Talents.LectureEcriture, 2, false),
            new Talent(Talents.Marchandage, 2, true),
            new Talent(Talents.ContreMalediction, 3, true),
            new Talent(Talents.DetectionArmes, 3, true),
            new Talent(Talents.DonLangues, 4, false),
            new Talent(Talents.TissageForgeron, 4, true),
            new Talent(Talents.AlterationArmeTir, 5, true),
            new Talent(Talents.Endurcissement, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.DetectionDefautsArmure, 6, true),
            new Talent(Talents.DissimulationArme, 6, false),
            new Talent(Talents.Desarmement, 7, false),
            new Talent(Talents.EndurcissementAutrui, 7, true),
            new Talent(Talents.AmeliorationLame, 8, true),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.LectureEcritureMagie, 8, false),
            new Talent(Talents.Incantation, 9, false),
            new Talent(Talents.MatriceAmelioree, 9, false),
            new Talent(Talents.TissageElementaliste, 9, false),
            new Talent(Talents.DetectionArmesMagiques, 10, true),
            new Talent(Talents.ProtectionContreMetal, 10, false),
            new Talent(Talents.PerfectionnementArmure, 11, true),
            new Talent(Talents.SangFeu, 11, false),
            new Talent(Talents.DeteriorationArme, 12, true),
            new Talent(Talents.RevelationDefautsArmure, 12, true),
            new Talent(Talents.AmeliorationArmure, 13, true),
            new Talent(Talents.AttaqueCritique, 13, false),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.MatriceRenforcee, 14, false),
            new Talent(Talents.PremierCerclePerfection, 14, true),
            new Talent(Talents.DeuxiemeChance, 15, false),
            new Talent(Talents.MatricePartagee, 15, false),
            new Talent(Talents.TrameAttribut, 15, false))),

    Guerrier("Guerrier",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, true),
            new Talent(Talents.AttaqueAcrobatique, 1, false),
            new Talent(Talents.CombatMainsNues, 1, true),
            new Talent(Talents.DanseAirs, 1, false),
            new Talent(Talents.PeauBois, 1, true),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.Endurance, 2, false, 9, 7),
            new Talent(Talents.Anticipation, 2, true),
            new Talent(Talents.ArmesJet, 2, false),
            new Talent(Talents.Esquive, 3, true),
            new Talent(Talents.VivaciteTigre, 3, false),
            new Talent(Talents.AttaquePlongeante, 4, true),
            new Talent(Talents.TissageGuerrier, 4, true),
            new Talent(Talents.CoupPiedRapide, 5, true),
            new Talent(Talents.MarcheVents, 5, false),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.ArmesTir, 6, false),
            new Talent(Talents.UltimeSursaut, 6, true),
            new Talent(Talents.DeuxiemeAttaque, 7, false),
            new Talent(Talents.PeauTellurique, 7, false),
            new Talent(Talents.AttaqueAstrale, 8, true),
            new Talent(Talents.AttaqueCobra, 8, true),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.DeuxiemeArme, 9, true),
            new Talent(Talents.DeviationProjectiles, 9, false),
            new Talent(Talents.PatteVelours, 9, false),
            new Talent(Talents.ArmeCorporelle, 10, true),
            new Talent(Talents.AttaqueMatrices, 10, false),
            new Talent(Talents.DetectionDefautsArmure, 11, false),
            new Talent(Talents.Vitalite, 11, false),
            new Talent(Talents.Cameleon, 12, false),
            new Talent(Talents.Desarconnement, 12, true),
            new Talent(Talents.PeauPierre, 13, true),
            new Talent(Talents.GuideElementaire, 13, false),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.AttaqueDecisive, 14, false),
            new Talent(Talents.DeuxiemeChance, 14, false),
            new Talent(Talents.AttaqueMultiple, 15, true),
            new Talent(Talents.AuraProtectrice, 15, false),
            new Talent(Talents.TrameAttribut, 15, false))),

    Illusionniste("Illusionniste",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.Incantation, 1, true),
            new Talent(Talents.LectureEcriture, 1, false),
            new Talent(Talents.LectureEcritureMagie, 1, true),
            new Talent(Talents.MatriceSort, 1, false),
            new Talent(Talents.MatriceSort, 1, false),
            new Talent(Talents.TissageIllusionniste, 1, true),
            new Talent(Talents.Endurance, 2, false, 4, 3),
            new Talent(Talents.DeguisementMagique, 2, true),
            new Talent(Talents.MatriceSort, 2, false),
            new Talent(Talents.DonLangues, 3, false),
            new Talent(Talents.MortFeinte, 3, true),
            new Talent(Talents.FauxSemblants, 4, true),
            new Talent(Talents.MatriceSort, 4, false),
            new Talent(Talents.Determination, 5, false),
            new Talent(Talents.RejetResponsabilite, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.Escamotage, 6, true),
            new Talent(Talents.VisionAstrale, 6, true),
            new Talent(Talents.Distraction, 7, true),
            new Talent(Talents.MatriceAmelioree, 7, false),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.MatriceAmelioree, 8, false),
            new Talent(Talents.VisionVeritable, 8, true),
            new Talent(Talents.DetectionMensonges, 9, true),
            new Talent(Talents.MatriceRenforcee, 9, false),
            new Talent(Talents.SangFroid, 9, true),
            new Talent(Talents.MemoireImages, 10, false),
            new Talent(Talents.OndeMentale, 10, true),
            new Talent(Talents.MatriceRenforcee, 11, false),
            new Talent(Talents.Hypnose, 11, true),
            new Talent(Talents.PenseeSecrete, 12, true),
            new Talent(Talents.VisageMiroir, 12, true),
            new Talent(Talents.AttaqueMatrices, 13, false),
            new Talent(Talents.MatricePartagee, 13, false),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.MatricePartagee, 14, false),
            new Talent(Talents.TissageMultiple, 14, true),
            new Talent(Talents.DeuxiemeChance, 15, true),
            new Talent(Talents.MatricePartagee, 15, false),
            new Talent(Talents.TrameAttribut, 15, false))),

    MaitreArmes("Maitre d'Armes",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, true),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.Esquive, 1, true),
            new Talent(Talents.Manoeuvre, 1, true),
            new Talent(Talents.Sarcasmes, 1, false),
            new Talent(Talents.Stabilite, 1, false),
            new Talent(Talents.Endurance, 2, false, 7, 6),
            new Talent(Talents.PremiereImpression, 2, false),
            new Talent(Talents.Riposte, 2, true),
            new Talent(Talents.ArmesJet, 3, false),
            new Talent(Talents.RireEncourageant, 3, false),
            new Talent(Talents.DonLangues, 4, false),
            new Talent(Talents.TissageMaitreArmes, 4, true),
            new Talent(Talents.DeuxiemeArme, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.SourireRavageur, 5, false),
            new Talent(Talents.Desarmement, 6, true),
            new Talent(Talents.Distraction, 6, false),
            new Talent(Talents.DeuxiemeAttaque, 7, true),
            new Talent(Talents.SangFroid, 7, true),
            new Talent(Talents.Anticipation, 8, false),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.SortieGracieuse, 8, false),
            new Talent(Talents.AttaqueAnnoncee, 9, true),
            new Talent(Talents.AttaqueCobra, 9, false),
            new Talent(Talents.ControleAdversaires, 9, true),
            new Talent(Talents.AttaqueCritique, 10, true),
            new Talent(Talents.AttaqueTornade, 10, true),
            new Talent(Talents.PerceArmure, 11, true),
            new Talent(Talents.ViveLame, 11, false),
            new Talent(Talents.DefenseAmelioree, 12, true),
            new Talent(Talents.UltimeSursaut, 12, false),
            new Talent(Talents.AttaqueAstrale, 13, false),
            new Talent(Talents.DefiChampion, 13, true),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.AttaqueMatrices, 14, false),
            new Talent(Talents.AttaqueMultiple, 14, true),
            new Talent(Talents.ArmeEtheree, 15, true),
            new Talent(Talents.AttaqueDecisive, 15, false),
            new Talent(Talents.TrameAttribut, 15, false))),

    MaitreAnimaux("Maitre des Animaux",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.Apprivoisement, 1, true),
            new Talent(Talents.Griffes, 1, true),
            new Talent(Talents.CombatMainsNues, 1, false),
            new Talent(Talents.DominationAnimaux, 1, true),
            new Talent(Talents.Pistage, 1, false),
            new Talent(Talents.Endurance, 2, false, 7, 6),
            new Talent(Talents.AnalyseCreature, 2, true),
            new Talent(Talents.Dressage, 2, true),
            new Talent(Talents.BondLezard, 3, true),
            new Talent(Talents.PatteVelours, 3, true),
            new Talent(Talents.RegardTerrifiantMaitre, 4, true), /* l'un OU */
            new Talent(Talents.SymboleAnimal, 4, true), /* l'autre */
            new Talent(Talents.TissageMaitreAnimaux, 4, true),
            new Talent(Talents.EmpruntSensoriel, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.SoinCompagnonAnimal, 5, true),
            new Talent(Talents.EnduranceFroid, 6, false),
            new Talent(Talents.AffolementTroupeaux, 6, true),
            new Talent(Talents.DechainementGriffes, 7, true),
            new Talent(Talents.DetectionPoison, 7, false),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.CoeurLion, 8, true),
            new Talent(Talents.ResistancePoison, 8, false),
            new Talent(Talents.ConstitutionBestiale, 9, false),
            new Talent(Talents.Hurlement, 9, true),
            new Talent(Talents.PossessionAnimal, 9, false),
            new Talent(Talents.CommandementAnimaux, 10, true),
            new Talent(Talents.EspritLion, 10, false), /* n'existe pas dans la liste de disciplines */
            new Talent(Talents.DressageMonture, 11, true), /* "domptage de monture" dans la liste des disciplines */
            new Talent(Talents.SensAnimal, 11, true),
            new Talent(Talents.Cameleon, 12, false),
            new Talent(Talents.RecuperationBestiale, 12, true),
            new Talent(Talents.DeuxiemeChance, 13, false),
            new Talent(Talents.Pietinement, 13, false),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.AttaqueAstrale, 14, false),
            new Talent(Talents.LocalisationEcho, 14, true),
            new Talent(Talents.ToileAstrale, 15, false),
            new Talent(Talents.TrameAttribut, 15, false),
            new Talent(Talents.Venin, 15, true))),

    NavigateurCiel("Navigateur du Ciel",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, true),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.AttaqueAcrobatique, 1, false),
            new Talent(Talents.Escalade, 1, true),
            new Talent(Talents.Esquive, 1, true),
            new Talent(Talents.NavigationAerienne, 1, true),
            new Talent(Talents.Endurance, 2, false, 6, 5),
            new Talent(Talents.ArmesJet, 2, false),
            new Talent(Talents.SautGeant, 2, true),
            new Talent(Talents.ChutePlume, 3, true),
            new Talent(Talents.Stabilite, 3, true),
            new Talent(Talents.CombatMainsNues, 4, false),
            new Talent(Talents.TissageNavigateurCiel, 4, true),
            new Talent(Talents.DanseAirs, 5, false),
            new Talent(Talents.Marchandage, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.Riposte, 6, false),
            new Talent(Talents.Sarcasmes, 6, false),
            new Talent(Talents.DeuxiemeArme, 7, false),
            new Talent(Talents.DonLangues, 7, true),
            new Talent(Talents.ArmesTir, 8, false),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.MarcheVents, 8, true),
            new Talent(Talents.CoeurLion, 9, true),
            new Talent(Talents.DeuxiemeAttaque, 9, false),
            new Talent(Talents.SangFroid, 9, true),
            new Talent(Talents.AttaqueBalancier, 10, false),
            new Talent(Talents.EnduranceFroid, 10, true),
            new Talent(Talents.DefenseAmelioree, 11, true), /* "défense" dans la liste des disciplines */
            new Talent(Talents.PerceArmure, 11, false), /* "Passe-bouclier" dans la liste des disciplines */
            new Talent(Talents.AttaqueCritique, 12, false),
            new Talent(Talents.UltimeSursaut, 12, true),
            new Talent(Talents.DestructionArme, 13, false),
            new Talent(Talents.DeuxiemeChance, 13, true),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.AttaqueMatrices, 14, false),
            new Talent(Talents.ViveLame, 14, false),
            new Talent(Talents.TirRapide, 15, false),
            new Talent(Talents.TrameAttribut, 15, false),
            new Talent(Talents.Vitalite, 15, true))),

    Necromancien("Nécromancien",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.Incantation, 1, true),
            new Talent(Talents.LectureEcriture, 1, false),
            new Talent(Talents.LectureEcritureMagie, 1, true),
            new Talent(Talents.MatriceSort, 1, false),
            new Talent(Talents.MatriceSort, 1, false),
            new Talent(Talents.TissageNecromancien, 1, true),
            new Talent(Talents.Endurance, 2, false, 4, 3),
            new Talent(Talents.RegardTerrifiant, 2, false),
            new Talent(Talents.VisionAstrale, 2, true),
            new Talent(Talents.LangueEsprits, 3, true),
            new Talent(Talents.MatriceSort, 3, false),
            new Talent(Talents.MatriceSort, 4, false),
            new Talent(Talents.PossessionAnimal, 4, false),
            new Talent(Talents.ImmobilisationEsprit, 5, true),
            new Talent(Talents.Invocation, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.DetectionVie, 6, true),
            new Talent(Talents.Determination, 6, false),
            new Talent(Talents.MatriceAmelioree, 7, false),
            new Talent(Talents.ParadeSpectrale, 7, true),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.EspritGuetteur, 8, true),
            new Talent(Talents.MatriceAmelioree, 8, false),
            new Talent(Talents.MarmonnementSibyllins, 9, false),
            new Talent(Talents.MatriceRenforcee, 9, false),
            new Talent(Talents.PocheAstrale, 9, true),
            new Talent(Talents.AnimationObjet, 10, false),
            new Talent(Talents.CercleInvocation, 10, true),
            new Talent(Talents.MatriceRenforcee, 11, false),
            new Talent(Talents.NegociationCreatureInvoquee, 11, true),
            new Talent(Talents.AttaqueMatrices, 12, true),
            new Talent(Talents.ProjectionAstrale, 12, true),
            new Talent(Talents.MatricePartagee, 13, false),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.VerrouCristallinSort, 13, true),
            new Talent(Talents.MatricePartagee, 14, false),
            new Talent(Talents.TissageMultiple, 14, true),
            new Talent(Talents.DestructionAme, 15, true),
            new Talent(Talents.MatricePartagee, 15, false),
            new Talent(Talents.TrameAttribut, 15, false))),

    Sorcier("Sorcier",
        Arrays.asList(new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.Incantation, 1, true),
            new Talent(Talents.LectureEcriture, 1, true),
            new Talent(Talents.LectureEcritureMagie, 1, true),
            new Talent(Talents.MatriceSort, 1, false),
            new Talent(Talents.MatriceSort, 1, false),
            new Talent(Talents.TissageSorcier, 1, false),
            new Talent(Talents.Endurance, 2, false, 4, 3),
            new Talent(Talents.AnalyseIndices, 2, true),
            new Talent(Talents.MatriceSort, 2, false),
            new Talent(Talents.MarmonnementSibyllins, 3, true),
            new Talent(Talents.MemoireLivresque, 3, true),
            new Talent(Talents.SouvenirsLivresques, 4, true),
            new Talent(Talents.VisionAstrale, 4, true),
            new Talent(Talents.Determination, 5, false),
            new Talent(Talents.LectureLevres, 5, false),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.DonLangues, 6, true),
            new Talent(Talents.MatriceAmelioree, 6, false),
            new Talent(Talents.DetectionVie, 7, true),
            new Talent(Talents.MaintienFilament, 7, true),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.MatriceAmelioree, 8, false),
            new Talent(Talents.SangFroid, 8, false),
            new Talent(Talents.AttaqueMatrices, 9, true),
            new Talent(Talents.ExtensionTrame, 9, true),
            new Talent(Talents.MatriceRenforcee, 9, false),
            new Talent(Talents.AttaqueAstrale, 10, true),
            new Talent(Talents.UltimeSursaut, 10, false),
            new Talent(Talents.MatriceRenforcee, 11, false),
            new Talent(Talents.TrameIncantation, 11, true),
            new Talent(Talents.MatriceRenforcee, 12, false),
            new Talent(Talents.TransfertBlessure, 12, true),
            new Talent(Talents.MatricePartagee, 13, false),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.VisionVeritable, 13, false),
            new Talent(Talents.EspritGuetteur, 14, true),
            new Talent(Talents.MatricePartagee, 14, false),
            new Talent(Talents.MatricePartagee, 15, false),
            new Talent(Talents.TrameAttribut, 15, false),
            new Talent(Talents.TrameEffet, 15, true))),

    Troubadour("Troubadour",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.ChantEmouvant, 1, true),
            new Talent(Talents.DeguisementMagique, 1, true),
            new Talent(Talents.ImitationVoix, 1, true),
            new Talent(Talents.PremiereImpression, 1, false),
            new Talent(Talents.Endurance, 2, false, 6, 5),
            new Talent(Talents.DonLangues, 2, true),
            new Talent(Talents.HistoireObjets, 2, false),
            new Talent(Talents.LectureEcriture, 3, true),
            new Talent(Talents.SensEmpathique, 3, true),
            new Talent(Talents.Sarcasmes, 4, false),
            new Talent(Talents.TissageTroubadour, 4, true),
            new Talent(Talents.ArmesJet, 5, false),
            new Talent(Talents.Distraction, 5, true),
            new Talent(Talents.RituelMaitreFantome, 5, true),
            new Talent(Talents.Marchandage, 6, false),
            new Talent(Talents.SangFroid, 6, true),
            new Talent(Talents.ArmesTir, 7, false),
            new Talent(Talents.ManipulationFoules, 7, true),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.Hypnose, 8, false),
            new Talent(Talents.SortieGracieuse, 8, false),
            new Talent(Talents.BarriereLames, 9, false),
            new Talent(Talents.VisionVeritable, 9, false),
            new Talent(Talents.VoixBarde, 9, true),
            new Talent(Talents.Multilinguisme, 10, false),
            new Talent(Talents.RejetResponsabilite, 10, true),
            new Talent(Talents.ChantProtection, 11, true),
            new Talent(Talents.TirImpressionnant, 11, false),
            new Talent(Talents.LienTelepathique, 12, false),
            new Talent(Talents.Reconstitution, 12, true),
            new Talent(Talents.JugementSang, 13, false),
            new Talent(Talents.DetectionInfluence, 13, true),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.LangueEsprits, 14, false),
            new Talent(Talents.UltimeSursaut, 14, false),
            new Talent(Talents.AuraProtectrice, 15, false),
            new Talent(Talents.ConfrontationHorreur, 15, true),
            new Talent(Talents.TrameAttribut, 15, false))),

    Voleur("Voleur",
        Arrays.asList(new Talent(Talents.ArmesMelee, 1, false),
            new Talent(Talents.RituelKarma, 1, false),
            new Talent(Talents.Crochetage, 1, true),
            new Talent(Talents.DeplacementSilencieux, 1, true),
            new Talent(Talents.Escalade, 1, false),
            new Talent(Talents.VolTire, 1, true),
            new Talent(Talents.Endurance, 2, false, 5, 4),
            new Talent(Talents.AttaqueSurprise, 2, true),
            new Talent(Talents.SensSerrures, 2, true),
            new Talent(Talents.Esquive, 3, true),
            new Talent(Talents.Recel, 3, true),
            new Talent(Talents.EsquivePieges, 4, true),
            new Talent(Talents.TissageVoleur, 4, true),
            new Talent(Talents.DesarmocagePieges, 5, true),
            new Talent(Talents.DetectionPieges, 5, false),
            new Talent(Talents.RituelMaitreFantome, 5, false),
            new Talent(Talents.DeguisementMagique, 6, false),
            new Talent(Talents.Escamotage, 6, true),
            new Talent(Talents.ArmesJet, 7, true),
            new Talent(Talents.DetectionArmes, 7, false),
            new Talent(Talents.ArmesTir, 8, false),
            new Talent(Talents.Commandement, 8, false),
            new Talent(Talents.RejetResponsabilite, 8, false),
            new Talent(Talents.DetectionOr, 9, false),
            new Talent(Talents.DissimulationArme, 9, true),
            new Talent(Talents.Sprint, 9, false),
            new Talent(Talents.DonLangues, 10, false),
            new Talent(Talents.PocheAstrale, 10, true),
            new Talent(Talents.LectureLevres, 11, true),
            new Talent(Talents.Stabilite, 11, false),
            new Talent(Talents.DetectionPoison, 12, true),
            new Talent(Talents.ViveLame, 12, false),
            new Talent(Talents.Cameleon, 13, false),
            new Talent(Talents.TirAvertissement, 13, false),
            new Talent(Talents.TramageTalent, 13, false),
            new Talent(Talents.DefenseAmelioree, 14, false),
            new Talent(Talents.Ricochet, 14, false),
            new Talent(Talents.ApprocheSurprise, 15, true),
            new Talent(Talents.TrameAttribut, 15, false),
            new Talent(Talents.VisionVeritable, 15, false)));


    private String label;
    private List<Talent> talents;

    private Disciplines(final String label, final List<Talent> talents)
    {
        this.label = label;
        this.talents = talents;
    }

    /**
     * @return the label
     */
    public String getLabel()
    {
        return label;
    }

    /**
     * @return the talents
     */
    public List<Talent> getTalents()
    {
        return talents;
    }
}
